import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {EventEmitter} from 'node:events';
import {createHostAdapter,offlineBundle} from '../src/modules/hardware/host-adapter.js';
import {ESP32_FIRMWARE_PROTOCOL} from '../src/services/firmware-constants.js';
function bundle(){const root=mkdtempSync(join(tmpdir(),'firmware-contract-'));for(const d of ['bin','data','user'])mkdirSync(join(root,d));writeFileSync(join(root,'bin/arduino-cli'),'test fixture executable, never run');const manifest={version:1,platform:'linux',arch:'arm64',protocol:ESP32_FIRMWARE_PROTOCOL,cliVersion:'1.3.1',coreVersion:'3.0.7',libraryVersion:'1.12.3',executable:'bin/arduino-cli',data:'data',user:'user',files:[{path:'bin/arduino-cli',sha256:createHash('sha256').update('test fixture executable, never run').digest('hex')}]};writeFileSync(join(root,'toolchain.json'),JSON.stringify(manifest));return {root,manifest};}
test('Pi and simulator provide the same discovery and firmware execution interface; simulation is explicit',async()=>{const seen=[],pi=createHostAdapter({platform:'linux',arch:'arm64',discover:()=>[{path:'/dev/ttyUSB0',deviceIdentity:'usb:A'}],runSync:(exe,args)=>{seen.push({exe,args});return {status:0};}}),sim=createHostAdapter({config:{firmwareSimulation:true}});assert.equal(pi.support().id,'raspberry-pi');assert.equal(pi.listDevices()[0].deviceIdentity,'usb:A');pi.configureSerial('/dev/ttyUSB0');assert.deepEqual(seen[0].args,['-F','/dev/ttyUSB0','115200','cs8','-cstopb','-parenb','-ixon','-ixoff','raw','-echo']);assert.equal(sim.listDevices()[0].deviceIdentity,'simulator:esp32');assert.equal((await sim.runFirmware(['compile'],{onOutput:t=>seen.push(t)})).simulated,true);assert.match(seen[1],/no compiler or physical device/);assert.throws(()=>sim.runFirmware(['core','install']),/offline compile/);assert.equal(sim.support().physicalVerified,false);assert.throws(()=>createHostAdapter({platform:'darwin'}).configureSerial('/dev/cu.test'),/supported on Linux/);});
test('offline bundle pins host, protocol, versions and hashes and rejects tampering',()=>{const f=bundle();assert.equal(offlineBundle(f.root,{platform:'linux',arch:'arm64'}).manifest.cliVersion,'1.3.1');assert.throws(()=>offlineBundle(f.root,{platform:'darwin',arch:'arm64'}),/does not match/);writeFileSync(join(f.root,'bin/arduino-cli'),'changed');assert.throws(()=>offlineBundle(f.root,{platform:'linux',arch:'arm64'}),/integrity/);});
test('firmware execution refuses missing tools, wrong version, nonzero exit and interruption; never installs dependencies',async()=>{const f=bundle();const spawnProcess=()=>{const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.kill=()=>child.emit('close',null);setTimeout(()=>child.emit('close',2),1);return child;};const host=createHostAdapter({config:{firmwareToolchainRoot:f.root},platform:'linux',arch:'arm64',spawnProcess,runSync:()=>({status:0,stdout:JSON.stringify({VersionString:'1.3.1'})})});assert.equal(host.verifyToolchain().ready,true);await assert.rejects(()=>host.runFirmware(['upload','-p','/dev/ttyUSB0']),/No success was assumed/);assert.throws(()=>host.runFirmware(['compile','--profile','remote']),/cannot fetch/);const wrong=createHostAdapter({config:{firmwareToolchainRoot:f.root},platform:'linux',arch:'arm64',runSync:()=>({status:0,stdout:'{"VersionString":"0.0"}'})});assert.throws(()=>wrong.verifyToolchain(),/version differs/);const hanging=createHostAdapter({spawnProcess:()=>{const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.kill=()=>queueMicrotask(()=>child.emit('close',null));return child;}});await assert.rejects(()=>hanging.runFirmware(['compile'],{timeoutMs:5}),/timed out/);});
