import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createDatabase} from '../src/db.js';
import {hashPassword} from '../src/services/auth.js';
import {createOperationsService} from '../src/modules/operations/service.js';
import {createHardwareService} from '../src/services/hardware.js';
import {createDisplayCoordinator} from '../src/services/display-coordinator.js';
import {createLocationSetupService} from '../src/modules/locations/service.js';
function fixture(){process.chdir(mkdtempSync(join(tmpdir(),'setup-test-')));const db=createDatabase({hashPassword,allowDemoInventorySeed:true});const work=createOperationsService({db});const logger={info(){},warn(){},error(){}};const hardware=createHardwareService({db,config:{hardwareAdapter:'simulator'},logger});let time=new Date();const display=createDisplayCoordinator({db,hardwareService:hardware,operationsService:work,clock:()=>time});const setup=createLocationSetupService({db,operationsService:work,displayCoordinator:display});const admin=db.prepare("SELECT * FROM users WHERE role='admin'").get(),op=db.prepare("SELECT * FROM users WHERE role='operator'").get(),controller=db.prepare('SELECT * FROM controllers LIMIT 1').get();db.prepare("UPDATE controllers SET heartbeat_status='online',module_count=20 WHERE id=?").run(controller.id);const command=(action,input={},user=admin)=>setup.command(user,action,{requestId:randomUUID(),...input});const selected=()=>setup.snapshot(admin).sessions[0];const label=()=>{const token=command('prepare',{quantity:1}).tokens[0];return `lytguide:${work.identity().site}:${token}:1`;};return{db,work,display,setup,admin,op,controller,command,selected,label,setTime:t=>time=t};}
test('light-first pairing is atomic, idempotent, retains existing cell stock and validates ownership',()=>{const f=fixture();f.command('start',{controllerId:f.controller.id});const s=f.selected(),c=f.db.prepare('SELECT * FROM cells WHERE controller_id=? AND hardware_channel=?').get(s.controller_id,s.output),qr=f.label();assert.throws(()=>f.command('light',{sessionId:s.id,generation:s.generation},f.op),/admin|permitted/i);const light=f.command('light',{sessionId:s.id,generation:s.generation});assert.equal(light.targets[0].status,'sent');const input={requestId:randomUUID(),sessionId:s.id,generation:s.generation,fieldSignature:f.setup.snapshot(f.admin).fieldSignature,label:qr,displayName:'Packing shelf बायाँ',physicalConfirmed:true,replaceLabel:true};const before=f.db.prepare('SELECT * FROM inventory_balances WHERE cell_id=?').all(c.id);const result=f.setup.command(f.admin,'bind',input);assert.equal(result.cellId,c.id);assert.equal(f.setup.command(f.admin,'bind',input).replayed,true);assert.deepEqual(f.db.prepare('SELECT * FROM inventory_balances WHERE cell_id=?').all(c.id),before);assert.ok(f.db.prepare('SELECT binding_verified_at FROM cells WHERE id=?').get(c.id).binding_verified_at);assert.throws(()=>f.command('bind',{...input,requestId:randomUUID()}),/changed/);f.db.close();});
test('unmapped outputs can be tested only by an owning setup receipt; skip/resume and duplicate labels',()=>{const f=fixture();f.db.prepare('UPDATE cells SET controller_id=NULL,hardware_channel=NULL WHERE controller_id=?').run(f.controller.id);f.command('start',{controllerId:f.controller.id});let s=f.selected();const light=f.command('light',{sessionId:s.id,generation:s.generation});assert.equal(light.targets[0].status,'sent');f.command('skip',{sessionId:s.id,generation:s.generation,reason:'Not lighting'});s=f.selected();assert.equal(s.output,2);f.command('retrySkipped',{sessionId:s.id,generation:s.generation});s=f.selected();assert.equal(s.output,1);const qr=f.label();f.command('light',{sessionId:s.id,generation:s.generation});const input={sessionId:s.id,generation:s.generation,fieldSignature:f.setup.snapshot(f.admin).fieldSignature,label:qr,displayName:'New bin',physicalConfirmed:true};const bound=f.command('bind',input);assert.ok(bound.cellId);s=f.selected();f.command('light',{sessionId:s.id,generation:s.generation});assert.throws(()=>f.command('bind',{...input,generation:s.generation,displayName:'Duplicate'}),/another location/);assert.throws(()=>f.command('bind',{...input,generation:s.generation,label:'https://evil.example/command'}),/Unsupported/);f.db.close();});
test('field revisions, required values, and controller replacement invalidate stale pairing',()=>{const f=fixture();f.command('field',{label:'Shed',fieldType:'text',required:true,enabled:true,useInDirections:true});assert.throws(()=>f.command('manual',{displayName:'Missing shed'}),/Enter Shed/);const field=f.setup.snapshot(f.admin).fields.find(v=>v.label==='Shed');const manual=f.command('manual',{displayName:'Shelf',attributes:{[field.field_key]:'पाँच'}});assert.match(f.setup.snapshot(f.admin).cells.find(c=>c.id===manual.cellId).description.directions,/पाँच/);f.command('start',{controllerId:f.controller.id});const s=f.selected();f.command('light',{sessionId:s.id,generation:s.generation});f.db.prepare('UPDATE controllers SET module_count=19 WHERE id=?').run(f.controller.id);assert.throws(()=>f.command('skip',{sessionId:s.id,generation:s.generation,reason:'skip'}),/configuration changed/);f.db.close();});
test('mixed quantities, owner-only stop, expiry and newer task generation protection',()=>{const f=fixture();const c=f.db.prepare('SELECT * FROM cells WHERE controller_id=? LIMIT 1').get(f.controller.id),ps=f.db.prepare('SELECT * FROM products LIMIT 2').all();f.db.exec('DELETE FROM inventory_balances');for(const p of ps)f.db.prepare('INSERT INTO inventory_balances(product_id,cell_id,available_quantity,reserved_quantity) VALUES(?,?,6,1)').run(p.id,c.id);let d=f.display.start(f.op,{kind:'quantity',cellId:c.id});assert.equal(d.targets[0].value,'LOC');assert.equal(d.targets[0].numeric,false);assert.throws(()=>f.display.stop(f.admin,d.id),/another operator/);f.display.stop(f.op,d.id);d=f.display.start(f.op,{kind:'quantity',cellId:c.id,productId:ps[0].id});assert.equal(d.targets[0].value,5);const before=f.db.prepare('SELECT COUNT(*) n FROM device_events').get().n;f.db.prepare("INSERT INTO work_guidance(cell_id,generation,desired,updated_at) VALUES(?,'new-task','{}',?)").run(c.id,new Date().toISOString());f.display.stop(f.op,d.id);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM device_events').get().n,before);d=f.display.start(f.op,{kind:'locate',cellId:c.id});f.setTime(new Date(Date.now()+121000));f.display.expire();assert.equal(f.display.status(f.op).length,0);f.db.close();});
test('recommendation actuals retain partial results, respect review boundaries and retry without duplicate reports',()=>{const f=fixture(),p=f.db.prepare('SELECT * FROM products LIMIT 1').get(),cells=f.db.prepare('SELECT * FROM cells LIMIT 2').all(),before=f.db.prepare('SELECT * FROM inventory_balances').all();const input={requestId:randomUUID(),productId:p.id,physicalConfirmed:true,reason:'Demo interrupted after picking two, put one',moves:[{sourceCellId:cells[0].id,targetCellId:cells[1].id,picked:2,put:1}]};const result=f.work.command(f.op,'recommendation',input);assert.equal(result.reportIds.length,2);assert.equal(f.work.command(f.op,'recommendation',input).replayed,true);assert.deepEqual(f.db.prepare('SELECT * FROM inventory_balances').all(),before);assert.deepEqual(f.db.prepare('SELECT quantity,direction,status FROM work_reports ORDER BY rowid').all().map(r=>({...r})),[{quantity:2,direction:'pick',status:'review'},{quantity:1,direction:'put',status:'review'}]);assert.throws(()=>f.work.command(f.op,'recommendation',{...input,requestId:randomUUID(),moves:[{...input.moves[0],picked:''}]}),/blank/);f.db.close();});

test('quantity displays preserve exact scoped balances and protect mappings during ownership', async()=>{
 const f=fixture(),cells=f.db.prepare('SELECT * FROM cells WHERE controller_id=? ORDER BY id LIMIT 4').all(f.controller.id),products=f.db.prepare('SELECT * FROM products LIMIT 2').all();
 f.db.exec('DELETE FROM inventory_balances');
 for(const [cell,p,q,reserved] of [[cells[0],products[0],6,1],[cells[1],products[0],2.5,0],[cells[2],products[0],1001,0],[cells[3],products[1],8,0]]) f.db.prepare('INSERT INTO inventory_balances(product_id,cell_id,available_quantity,reserved_quantity) VALUES(?,?,?,?)').run(p.id,cell.id,q,reserved);
 const before=f.db.prepare('SELECT * FROM inventory_balances').all();
 const id=randomUUID(),display=f.display.start(f.op,{kind:'quantity',productId:products[0].id},{requestId:id});
 assert.deepEqual(display.targets.map(t=>t.cellId),cells.slice(0,3).map(c=>c.id));
 assert.equal(display.targets[0].value,5);assert.equal(display.targets[0].color,'yellow');assert.equal(display.targets[0].numeric,true);
 assert.equal(display.targets[1].numeric,false);assert.equal(display.targets[2].numeric,false);
 assert.ok(display.targets.every(t=>t.status==='sent'));
 assert.deepEqual(f.display.view(f.op,{cellId:cells[1].id})[0].products.map(p=>p.available),[2.5]);
 const events=f.db.prepare('SELECT COUNT(*) n FROM device_events').get().n;
 f.display.start(f.op,{kind:'quantity',productId:products[0].id},{requestId:id});
 assert.equal(f.db.prepare('SELECT COUNT(*) n FROM device_events').get().n,events);
 const {guardSetupChange}=await import('../src/modules/operations/guards.js');
 assert.throws(()=>guardSetupChange(f.db,{cellId:cells[0].id}),/active utility display/);
 f.display.stop(f.op,id);assert.doesNotThrow(()=>guardSetupChange(f.db,{cellId:cells[0].id}));
 assert.deepEqual(f.db.prepare('SELECT * FROM inventory_balances').all(),before);
 f.db.close();
});

test('zero declared outputs cannot begin setup despite existing mappings and do not emit hardware commands',()=>{
 const f=fixture();f.db.prepare('UPDATE controllers SET module_count=0 WHERE id=?').run(f.controller.id);const mapped=f.db.prepare('SELECT id,controller_id,hardware_channel FROM cells WHERE controller_id=?').all(f.controller.id),events=f.db.prepare('SELECT COUNT(*) n FROM device_events').get().n;
 assert.ok(mapped.length>0);assert.throws(()=>f.command('start',{controllerId:f.controller.id}),/output count/);assert.equal(f.setup.snapshot(f.admin).sessions.length,0);assert.deepEqual(f.db.prepare('SELECT id,controller_id,hardware_channel FROM cells WHERE controller_id=?').all(f.controller.id),mapped);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM device_events').get().n,events);f.db.close();
});

test('opening quantity scopes only reads balances and selecting a product stays distinct from starting a display',async()=>{
 const f=fixture(),{displayRoutes}=await import('../src/modules/stocktaking/display-routes.js');
 const c=f.db.prepare('SELECT * FROM cells LIMIT 1').get(),p=f.db.prepare('SELECT * FROM products LIMIT 1').get();
 f.db.prepare('UPDATE inventory_balances SET available_quantity=3,reserved_quantity=3 WHERE cell_id=? AND product_id=?').run(c.id,p.id);
 const balances=f.db.prepare('SELECT * FROM inventory_balances').all(),events=f.db.prepare('SELECT COUNT(*) n FROM device_events').get().n;
 const render=(query,user=f.op)=>{const res={body:'',writeHead(){},end(v){this.body=v;}};assert.equal(displayRoutes({method:'GET'},res,new URL('http://localhost/quantities'+query),user,{displayCoordinator:f.display}),true);return res.body;};
 const selected=render(`?cellId=${c.id}&productId=${p.id}`);
 assert.match(selected,/On shelf 3 · Reserved 3 · Available to pick 0/);assert.match(selected,/Selected product at this location/);assert.match(selected,/Start quantity display/);assert.doesNotMatch(selected,/Show this product on LED|Select this product at this location/);
 assert.match(render(`?cellId=${c.id}`),/Select this product at this location/);
 assert.match(render(`?productId=${p.id}`),/Selected product across its locations/);
 assert.match(render(''),/Entire warehouse/);assert.match(render(`?kind=locate&cellId=${c.id}`),/Start locator display/);
 const readOnly={...f.op,capabilities:['locations.view']};assert.doesNotMatch(render(`?cellId=${c.id}&productId=${p.id}`,readOnly),/data-display-start/);
 assert.deepEqual(f.db.prepare('SELECT * FROM inventory_balances').all(),balances);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM device_events').get().n,events);f.db.close();
});
