import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../public/client/work.js',import.meta.url),'utf8').replace('export async function mount() {','').split('let syncing=false;')[0];
function client(){
 const status={textContent:'',innerHTML:'',attrs:{},setAttribute(k,v){this.attrs[k]=v;}},disclosure={open:false},details={innerHTML:'',querySelector:()=>disclosure};
 const box={hidden:true,querySelector:s=>s==='[data-stock-status]'?status:details};const form={dataset:{workAction:'create'},elements:{productId:{value:'1'},direction:{value:'pick'},quantity:{value:'7'}},querySelector:s=>s==='[data-product-stock]'?box:null};
 const root={querySelectorAll:()=>[form]},requests=[];let clock=Date.now();const context=vm.createContext({document:{querySelector:s=>s==='#work-app'?root:null},crypto:{randomUUID:()=> 'device'},localStorage:{getItem:()=> 'device',setItem(){}},URLSearchParams,location:{pathname:'/pick',search:''},Date:class extends Date{static now(){return clock;}},Map,AbortSignal,encodeURIComponent,fetch:(url,options)=>new Promise((resolve,reject)=>requests.push({url,options,resolve,reject}))});vm.runInContext(source,context);const run=s=>vm.runInContext(s,context);run("snapshot={site:'site',dataset:'data',user:{id:1},products:[]};online=true");context.form=form;
 const data=(id,recorded=12)=>({site:'site',dataset:'data',actorId:1,productId:id,recorded,spaceForMore:22,totalCapacity:recorded+22,pickReserved:3,incomingReserved:2,availableToPick:recorded-3,putCapacity:20,unit:'cases',generatedAt:new Date().toISOString(),reservationCount:1,reservations:[{taskId:7,kind:'pick',quantity:3,unit:'cases',location:'A1'}],detailScope:'own',unavailableUnreserved:0});
 return {run,context,form,box,status,details,disclosure,requests,data,advance:ms=>{clock+=ms;},finish:async(index,id,stock)=>{requests[index].resolve({ok:true,json:async()=>data(id,stock)});await run(`productStockReads.get(stockReadKey('${id}')).promise`);}};
}
test('selected/restored picker shows spinner until fresh no-store GET resolves; input and passive task links survive',async()=>{
 const c=client();c.run('refreshProductStocks()');assert.match(c.status.innerHTML,/stock-spinner/);assert.equal(c.status.attrs['aria-busy'],'true');assert.equal(c.requests[0].options.cache,'no-store');assert.equal(c.requests[0].options.method,undefined);await c.finish(0,1);assert.match(c.status.innerHTML,/Current Stock<\/dt><dd>12/);assert.match(c.status.innerHTML,/Space for More<\/dt><dd>20/);assert.match(c.status.innerHTML,/Total Capacity<\/dt><dd>34/);assert.match(c.status.innerHTML,/Reserved for Pick: <strong>3/);assert.match(c.status.innerHTML,/Reserved for Put: <strong>2/);assert.equal(c.status.attrs['aria-busy'],'false');assert.match(c.details.innerHTML,/href="\/tasks\/7"/);assert.doesNotMatch(c.details.innerHTML,/What do these figures mean|stock-definitions/);assert.match(c.details.innerHTML,/data-disclosure="product-stock-details"/);assert.doesNotMatch(c.details.innerHTML,/data-work-action|data-active-location/);assert.equal(c.form.elements.quantity.value,'7');
});
test('rapid selection never paints the previous product; empty selection stays empty after pending response',async()=>{
 const c=client();c.run('refreshProductStocks()');c.form.elements.productId.value='2';c.run('refreshProductStocks(true,form)');await c.finish(0,1,99);assert.match(c.status.innerHTML,/Loading current stock/);assert.doesNotMatch(c.status.innerHTML,/99/);await c.finish(1,2,6);assert.match(c.status.innerHTML,/Current Stock<\/dt><dd>6/);
 c.form.elements.productId.value='3';c.run('refreshProductStocks(true,form)');c.form.elements.productId.value='';c.run('refreshProductStocks(true,form)');await c.finish(2,3);assert.equal(c.box.hidden,true);assert.equal(c.requests.length,3);
});
test('error and offline states never present old counts as current; explicit retry and periodic refresh preserve details and edits',async()=>{
 const c=client();c.run('refreshProductStocks()');await c.finish(0,1);c.disclosure.open=true;c.advance(31000);c.run('refreshProductStocks()');assert.match(c.status.innerHTML,/Loading/);assert.doesNotMatch(c.status.innerHTML,/Current Stock/);c.requests[1].reject(new Error('offline'));await c.run("productStockReads.get(stockReadKey('1')).promise");assert.match(c.status.innerHTML,/Retry stock check/);c.run('refreshProductStocks()');assert.equal(c.requests.length,2);
 c.run('online=false;refreshProductStocks()');assert.match(c.status.textContent,/Offline/);assert.equal(c.requests.length,2);c.run('online=true;refreshProductStocks(true,form)');await c.finish(2,1,14);assert.match(c.status.innerHTML,/Current Stock<\/dt><dd>14/);assert.equal(c.disclosure.open,true);assert.equal(c.form.elements.quantity.value,'7');
});
test('wrong actor/dataset response is discarded and assignment direction uses the same read with separate put space',async()=>{
 const c=client();c.form.dataset.workAction='assign';c.form.elements.direction.value='put';c.run('refreshProductStocks()');c.requests[0].resolve({ok:true,json:async()=>({...c.data(1),actorId:2})});await c.run("productStockReads.get(stockReadKey('1')).promise");assert.match(c.status.innerHTML,/Stock unavailable/);assert.doesNotMatch(c.status.innerHTML,/Current Stock/);c.run('refreshProductStocks(true,form)');await c.finish(1,1);assert.match(c.status.innerHTML,/Space for More<\/dt><dd>20/);assert.match(c.details.innerHTML,/Physical Free Space: 22/);c.run("snapshot.dataset='new';refreshProductStocks()");assert.equal(c.requests.length,3);assert.match(c.status.innerHTML,/Loading/);
});

test('A to B to A starts a new read and ignores the older A response',async()=>{
 const c=client();c.run('refreshProductStocks()');const old=c.run("productStockReads.get(stockReadKey('1')).promise");c.form.elements.productId.value='2';c.run('refreshProductStocks(true,form)');c.form.elements.productId.value='1';c.run('refreshProductStocks(true,form)');assert.equal(c.requests.length,3);c.requests[0].resolve({ok:true,json:async()=>c.data(1,99)});await old;assert.match(c.status.innerHTML,/Loading/);assert.doesNotMatch(c.status.innerHTML,/99/);await c.finish(2,1,8);assert.match(c.status.innerHTML,/Current Stock<\/dt><dd>8/);
});
test('cached and in-flight team details cannot paint after permissions change',async()=>{
 const c=client();c.run("snapshot.capabilities={view:true,pick:true,teamView:true};refreshProductStocks()");const old=c.run("productStockReads.get(stockReadKey('1')).promise");c.run('snapshot.capabilities.teamView=false;refreshProductStocks()');assert.equal(c.requests.length,2);c.requests[0].resolve({ok:true,json:async()=>({...c.data(1),detailScope:'team',reservations:[{taskId:999,kind:'pick',quantity:1,unit:'cases',assignee:'Other user'}]})});await old;assert.doesNotMatch(c.details.innerHTML,/999|Other user/);await c.finish(1,1);assert.doesNotMatch(c.details.innerHTML,/999|Other user/);
 c.run('snapshot.capabilities.pick=false;refreshProductStocks()');assert.equal(c.box.hidden,true);assert.equal(c.details.innerHTML,'');assert.equal(c.requests.length,2);
});
