import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createDatabase} from '../src/db.js';
import {hashPassword} from '../src/services/auth.js';
import {createOperationsService} from '../src/modules/operations/service.js';
import {createAccessService,currentActor} from '../src/modules/access/service.js';
import {createCell} from '../src/services/inventory.js';
function fixture(){
 process.chdir(mkdtempSync(join(tmpdir(),'returned-work-')));const db=createDatabase({hashPassword,allowDemoInventorySeed:true}),work=createOperationsService({db});
 const admin=db.prepare("SELECT * FROM users WHERE role='admin'").get(),op=db.prepare("SELECT * FROM users WHERE role='operator'").get();
 db.prepare("INSERT INTO users(name,username,password_hash,role,status,created_at) VALUES('Receiver','receiver',?,'operator','active',?)").run(hashPassword('test'),new Date().toISOString());const other=db.prepare("SELECT * FROM users WHERE username='receiver'").get();
 db.exec('DELETE FROM inventory_balances');const cells=db.prepare('SELECT * FROM cells WHERE active=1 ORDER BY id LIMIT 2').all();db.prepare('UPDATE products SET items_per_cell=3 WHERE id=1').run();for(const c of cells)db.prepare('INSERT INTO inventory_balances(product_id,cell_id,available_quantity,reserved_quantity) VALUES(1,?,20,0)').run(c.id);
 const cmd=(u,a,i={})=>work.command(u,a,{requestId:randomUUID(),...i}),get=id=>work.task(admin,id),fields=t=>({taskId:t.id,generation:t.assignment_generation,returnEventId:t.return_event?.id,progressToken:t.progress_token});
 const create=(direction='pick',self=false,qty=5)=>{if(direction==='pick'){db.prepare('UPDATE inventory_balances SET available_quantity=3 WHERE cell_id=?').run(cells[0].id);}else db.exec('DELETE FROM inventory_balances');const id=cmd(self?op:admin,'create',{direction,productId:1,quantity:qty,...(!self?{assigneeId:op.id}:{})}).taskId;if(!self)cmd(op,'start',fields(get(id)));return get(id);};
 const finish=(t,quantity=2)=>{let l=t.lines[0];cmd(op,'acquire',{lineId:l.id,revision:l.revision,method:'arrival',deviceId:'original'});l=get(t.id).lines[0];cmd(op,'report',{lineId:l.id,revision:l.revision,cellId:l.cell_id,unit:l.unit_of_measure,quantity,deviceId:'original'});return get(t.id);};
 const physical=()=>({ledger:db.prepare('SELECT * FROM transactions').all(),reservations:db.prepare('SELECT * FROM work_reservations').all(),turns:db.prepare('SELECT * FROM cell_turns').all()});return {db,work,admin,op,other,cmd,get,fields,create,finish,physical,cells};
}
for(const direction of ['pick','put'])test(`${direction}: partial return preserves actuals, acknowledgement is seen-only, editable remainder is idempotent and due is retained`,()=>{
 const f=fixture();let t=f.finish(f.create(direction));assert.equal(t.recorded_quantity,2);const due=t.due_at;f.cmd(f.op,'handBack',{...f.fields(t),reason:'Unable to finish',note:'Shift ended'});t=f.get(t.id);assert.equal(t.remaining_quantity,3);assert.equal(t.attention,0);assert.equal(t.assignment_state,'returned');
 const before=f.physical();f.cmd(f.admin,'acknowledgeReturn',f.fields(t));f.cmd(f.admin,'acknowledgeReturn',f.fields(t));assert.deepEqual(f.physical(),before);assert.equal(f.get(t.id).assignment_history.filter(e=>e.event_type==='return_acknowledged').length,1);assert.equal(f.work.snapshot(f.admin,{view:'mine'}).returnedTasks[0].id,t.id);assert.equal(f.work.snapshot(f.op,{view:'mine'}).returnedTasks.length,0);
 const input={...f.fields(t),remainingQuantity:4,assigneeId:f.other.id,requestId:randomUUID()};f.work.command(f.admin,'updateReturned',input);assert.equal(f.work.command(f.admin,'updateReturned',input).replayed,true);let updated=f.get(t.id);assert.equal(updated.requested_quantity,6);assert.equal(updated.recorded_quantity,2);assert.equal(updated.remaining_quantity,4);assert.equal(updated.due_at,due);assert.deepEqual(f.physical().ledger,before.ledger);assert.equal(updated.lines.filter(l=>l.execution_state==='ready').reduce((n,l)=>n+l.reserved,0),4);
 f.cmd(f.other,'handBack',f.fields(updated));assert.throws(()=>f.cmd(f.admin,'acknowledgeReturn',{...f.fields(f.get(t.id)),returnEventId:t.return_event.id}),/return changed/);f.db.close();
});
test('stale progress rejects quantity correction or new evidence without mutating plans; self return retains review',()=>{
 const f=fixture();let t=f.finish(f.create());f.cmd(f.op,'handBack',f.fields(t));t=f.get(t.id);const stale={...f.fields(t),remainingQuantity:3,assigneeId:f.other.id};const l=t.lines.find(l=>l.execution_state==='settled');f.cmd(f.admin,'correct',{lineId:l.id,revision:l.revision,quantity:1,verification:'Checked actual slip'});const before=f.physical();assert.throws(()=>f.cmd(f.admin,'updateReturned',stale),/quantities or assignment changed/);assert.deepEqual(f.physical(),before);
 t=f.create('pick',true,1);f.cmd(f.op,'askReview',{lineId:t.lines[0].id,reason:'Possibly moved'});f.cmd(f.op,'handBack',f.fields(f.get(t.id)));t=f.get(t.id);assert.equal(t.attention,1);assert.equal(t.assignment_state,'returned');assert.throws(()=>f.cmd(f.admin,'updateReturned',{...f.fields(t),remainingQuantity:1,assigneeId:f.other.id}),/Check moved quantity first/);f.db.close();
});
for(const direction of ['pick','put'])test(direction+' review responsibility transfers without execution; observations preserve performer, late evidence survives, verified remainder can resume',()=>{
 const f=fixture();let t=f.create(direction);const original=t.lines[0];f.cmd(f.op,'acquire',{lineId:original.id,revision:original.revision,method:'arrival',deviceId:'original'});t=f.get(t.id);const old=t.lines[0];f.cmd(f.op,'askReview',{lineId:old.id,reason:'Need to check moved quantity'});t=f.get(t.id);const before=f.physical(),snapshots=f.db.prepare('SELECT id,instruction_snapshot,revision,instruction_owner FROM task_lines WHERE task_id=?').all(t.id);
 const transfer={...f.fields(t),assigneeId:f.other.id,requestId:randomUUID()};f.work.command(f.admin,'assignReview',transfer);assert.equal(f.work.command(f.admin,'assignReview',transfer).replayed,true);assert.deepEqual(f.physical(),before);assert.deepEqual(f.db.prepare('SELECT id,instruction_snapshot,revision,instruction_owner FROM task_lines WHERE task_id=?').all(t.id),snapshots);t=f.get(t.id);assert.equal(t.assignee_id,f.other.id);assert.equal(t.review_followup,1);const assignedBy=t.assigned_by,assignedAt=t.assigned_at;assert.throws(()=>f.cmd(f.other,'start',f.fields(t)),/Check moved quantity first/);assert.throws(()=>f.cmd(f.other,'cancel',{lineId:t.lines[1].id,revision:t.lines[1].revision}),/Check moved quantity first/);assert.ok(f.work.snapshot(f.other,{view:'mine'}).tasks.some(x=>x.id===t.id));assert.equal(t.lines[0].canAct,false);
 assert.throws(()=>f.cmd(f.other,'acquire',{lineId:old.id,revision:old.revision,method:'arrival',deviceId:'new'}),/Check moved quantity first/);assert.throws(()=>f.cmd(f.op,'acquire',{lineId:old.id,revision:old.revision,method:'arrival',deviceId:'original'}),/current assigned/);
 f.cmd(f.other,'observeReview',{...f.fields(t),lineId:old.id,quantity:2,note:'Original operator confirms two moved'});assert.equal(f.get(t.id).review_observations[0].observer_name,'Receiver');assert.deepEqual(f.physical(),before);
 const late=f.cmd(f.op,'report',{lineId:old.id,revision:old.revision,cellId:old.cell_id,unit:old.unit_of_measure,quantity:2,deviceId:'original',assignmentGeneration:old.current_generation});assert.equal(late.status,'review');assert.equal(f.db.prepare('SELECT performer_id FROM work_reports WHERE id=?').get(late.reportId).performer_id,f.op.id);
 const caseInfo=f.work.snapshot(f.admin,{reportId:late.reportId}).pending[0];assert.ok(caseInfo.reviewFollowup);assert.equal(caseInfo.observations.length,1);assert.throws(()=>f.cmd(f.other,'resolve',{reportId:late.reportId,quantity:2,verification:'Checked'}),/not permitted/);assert.throws(()=>f.cmd(f.admin,'resolve',{reportId:late.reportId,quantity:2,verification:'Checked'}),/original worker has stopped/);
 f.cmd(f.admin,'resolve',{reportId:late.reportId,quantity:2,verification:'Spoke with original operator',workerStopped:true});t=f.get(t.id);assert.equal(t.recorded_quantity,2);assert.equal(t.attention,0);assert.equal(t.completed_at,null);assert.equal(t.lines[0].attribution.performer,f.op.name);f.cmd(f.other,'resumeFollowup',f.fields(t));t=f.get(t.id);assert.equal(t.review_followup,0);assert.equal(t.assigned_by,assignedBy);assert.equal(t.assigned_at,assignedAt);assert.equal(t.assignment_state,'offered');assert.equal(t.remaining_quantity,3);assert.equal(t.lines.filter(l=>l.execution_state==='ready').reduce((n,l)=>n+l.planned_quantity,0),3);f.db.close();
});
test('returned queue pages globally, delegates retain scope and independent permissions, stale review transfer rejects',()=>{
 const f=fixture(),access=createAccessService({db:f.db}),role=access.saveRole(f.admin,{name:'Assignment delegate',capabilities:['work.view','work.assign','work.pick']});access.assign(f.admin,{userId:f.other.id,roleId:role});const delegate=currentActor(f.db,f.other);
 for(let i=0;i<103;i++){const id=f.cmd(f.admin,'create',{direction:'pick',productId:1,quantity:.001,assigneeId:f.op.id}).taskId;f.cmd(f.op,'decline',f.fields(f.get(id)));}
 assert.equal(f.work.snapshot(f.admin,{view:'mine'}).returnedTasks.length,100);assert.equal(f.work.snapshot(f.admin,{view:'mine',returnedPage:2}).returnedTasks.length,3);const older=f.work.snapshot(f.admin,{view:'mine',returnedPage:2}).returnedTasks.at(-1);assert.equal(f.work.snapshot(f.admin,{view:'mine'}).returnedTasks.some(t=>t.id===older.id),false);assert.equal(f.work.snapshot(f.admin,{taskId:older.id}).tasks[0].id,older.id);assert.equal(f.work.snapshot(delegate,{view:'mine'}).returnedTasks.length,0);
 let t=f.work.snapshot(f.admin,{view:'mine'}).returnedTasks[0];assert.throws(()=>f.cmd(delegate,'acknowledgeReturn',f.fields(t)),/another operator/);assert.throws(()=>f.cmd(f.op,'updateReturned',{...f.fields(t),remainingQuantity:1,assigneeId:f.op.id}),/not permitted/);
 const id=f.cmd(delegate,'create',{direction:'pick',productId:1,quantity:.001,assigneeId:f.op.id}).taskId;f.cmd(f.op,'decline',f.fields(f.get(id)));t=f.get(id);assert.equal(f.work.snapshot(delegate,{view:'mine'}).returnedTasks[0].id,id);f.cmd(delegate,'acknowledgeReturn',f.fields(t));assert.throws(()=>f.cmd(delegate,'updateReturned',{...f.fields(t),remainingQuantity:.001,assigneeId:f.op.id,changeDue:true,dueAt:'2027-01-01T00:00:00Z'}),/not permitted/);f.db.close();
});
test('location details create/edit feed new instruction snapshots without rewriting existing instructions or attributes',()=>{
 const f=fixture(),c=createCell(f.db,{logicalCode:'SHED-01',travelInstructions:'Shed A, shelf 2'});assert.equal(c.travel_instructions,'Shed A, shelf 2');f.db.prepare("INSERT INTO location_field_definitions(field_key,label,field_type,use_in_directions) VALUES('aisle','Aisle','text',1)").run();f.db.prepare("INSERT INTO location_field_values VALUES(?, 'aisle', '\"East\"')").run(c.id);
 const make=()=>f.get(f.cmd(f.op,'create',{direction:'put',productId:1,quantity:1,preferredCellId:c.id}).taskId);const old=make(),snapshot=old.lines[0].instruction_snapshot;
 f.cmd(f.admin,'locationDetails',{cellId:c.id,descriptionRevision:c.description_revision,travelInstructions:'Shed B, shelf 3'});assert.equal(f.db.prepare('SELECT COUNT(*) n FROM location_field_values WHERE cell_id=?').get(c.id).n,1);assert.equal(f.get(old.id).lines[0].instruction_snapshot,snapshot);assert.match(make().lines[0].directions.directions,/Shed B, shelf 3/);assert.match(make().lines[0].directions.directions,/Aisle East/);f.db.close();
});

test('review-only recipient cannot post a correction to another performer’s completed cell',()=>{
 const f=fixture();let t=f.finish(f.create());const completed=t.lines.find(l=>l.execution_state==='settled'),pending=t.lines.find(l=>l.execution_state==='ready');f.cmd(f.op,'askReview',{lineId:pending.id,reason:'Check original movement'});t=f.get(t.id);f.cmd(f.admin,'assignReview',{...f.fields(t),assigneeId:f.other.id});const before=f.physical();assert.throws(()=>f.cmd(f.other,'correct',{lineId:completed.id,revision:completed.revision,quantity:1,verification:'Observed one moved'}),/observation only/);assert.deepEqual(f.physical(),before);assert.equal(f.get(t.id).recorded_quantity,2);assert.equal(f.get(t.id).lines.find(l=>l.id===completed.id).attribution.performer,f.op.name);f.db.close();
});

test('acknowledgement keeps returns visible; explicit safe closure removes them while uncertainty stays visible',()=>{
 const f=fixture();let t=f.create();f.cmd(f.op,'handBack',f.fields(t));t=f.get(t.id);f.cmd(f.admin,'acknowledgeReturn',f.fields(t));assert.ok(f.work.snapshot(f.admin).returnedTasks.some(x=>x.id===t.id));f.cmd(f.admin,'stop',f.fields(t));assert.equal(f.work.snapshot(f.admin).returnedTasks.some(x=>x.id===t.id),false);assert.ok(f.work.snapshot(f.admin,{view:'history',scope:'team'}).tasks.some(x=>x.id===t.id));
 t=f.create();f.cmd(f.op,'askReview',{lineId:t.lines[0].id,reason:'Unknown moved quantity'});f.cmd(f.op,'handBack',f.fields(f.get(t.id)));f.cmd(f.admin,'stop',f.fields(f.get(t.id)));assert.ok(f.work.snapshot(f.admin).returnedTasks.some(x=>x.id===t.id));f.db.close();
});
