import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
const source=readFileSync(new URL('../public/client/stocktaking.js',import.meta.url),'utf8').split("root.addEventListener('submit'")[0];
function storage(){const map=new Map();return{get length(){return map.size;},key:n=>[...map.keys()][n],getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};}
function device(localStorage,fetch){const snapshot={site:'test',dataset:'generation',user:{id:1},capabilities:{},runs:[],cells:[],products:[],counters:[]},root={};const context=vm.createContext({document:{querySelector:q=>q==='#stocktaking-app'?root:{textContent:JSON.stringify(snapshot)}},location:{search:'',pathname:'/stocktaking'},localStorage,crypto:{randomUUID},URLSearchParams,AbortSignal,window:{dispatchEvent(){}},Event:class{},fetch});vm.runInContext(source+'\nrender=()=>{};globalThis.api={submit,sync,queue};',context);return{context,api:context.api,snapshot};}
test('a stale second tab cannot erase a first tab’s unsent count or confirmed receipt',async()=>{const shared=storage(),offline=async()=>{throw new Error('offline');},a=device(shared,offline),b=device(shared,offline);await a.api.submit('observe',{attemptId:'a',lines:[{actual:2}]},'draft-a');await b.api.submit('observe',{attemptId:'b',lines:[{actual:3}]},'draft-b');assert.equal(a.api.queue().length,2);assert.equal(b.api.queue().length,2);const fresh=device(shared,offline);assert.equal(fresh.api.queue().length,2);assert.equal(JSON.stringify(fresh.api.queue().map(q=>q.input.attemptId).sort()),JSON.stringify(['a','b']));});
test('a submission arriving during a refresh is drained and acknowledged with its original receipt',async()=>{const shared=storage(),requests=[];let unblock;const gate=new Promise(r=>unblock=r);let snapshots=0,d;d=device(shared,async(url,options)=>{if(url.endsWith('/snapshot')){if(++snapshots===1)await gate;return{ok:true,json:async()=>d.snapshot};}const input=JSON.parse(options.body);requests.push(input);return{ok:true,json:async()=>({status:'review',message:'received'})};});const refreshing=d.api.sync();const submission=d.api.submit('observe',{attemptId:'during-refresh',lines:[{actual:4}]},'draft');unblock();await Promise.all([refreshing,submission]);assert.equal(requests.length,1);assert.equal(d.api.queue()[0].input.requestId,requests[0].requestId);assert.equal(d.api.queue()[0].result.status,'review');});
