import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createDatabase} from '../src/db.js';
import {hashPassword} from '../src/services/auth.js';
import {createOperationsService} from '../src/modules/operations/service.js';
import {createMaintenanceCommands} from '../src/modules/maintenance/service.js';
import {createAccessService} from '../src/modules/access/service.js';
import {navigation} from '../src/modules/access/catalog.js';
function fixture(){process.chdir(mkdtempSync(join(tmpdir(),'lightguide-work-refined-')));const db=createDatabase({hashPassword,allowDemoInventorySeed:true}),work=createOperationsService({db});const admin=db.prepare("SELECT * FROM users WHERE role='admin'").get(),op=db.prepare("SELECT * FROM users WHERE role='operator'").get();for(const username of ['second','third'])db.prepare("INSERT INTO users(name,username,password_hash,role,status,created_at) VALUES('Same Name',?,?,'operator','active',?)").run(username,hashPassword('test'),new Date().toISOString());const second=db.prepare("SELECT * FROM users WHERE username='second'").get(),third=db.prepare("SELECT * FROM users WHERE username='third'").get();const cmd=(u,a,i={})=>work.command(u,a,{requestId:randomUUID(),...i}),create=(u,i={})=>cmd(u,'create',{direction:'pick',productId:1,quantity:.001,...i});return {db,work,admin,op,second,third,cmd,create};}
test('three operators: untouched decline returns once, reassign preserves deadline/history, own cancellation makes no review case',()=>{const f=fixture();assert.equal(navigation(f.admin)[0][1],'/work');const id=f.create(f.admin,{quantity:4,assigneeId:f.op.id}).taskId;let t=f.work.task(f.admin,id);const due=t.due_at;f.cmd(f.op,'decline',{taskId:id,generation:t.assignment_generation,reason:'Busy'});assert.equal(f.work.snapshot(f.op,{view:'mine'}).tasks.length,0);let team=f.work.snapshot(f.admin,{view:'team',state:'needs_assignment'});assert.equal(team.tasks.length,1);assert.equal(team.reviewTotal,0);t=team.tasks[0];f.cmd(f.admin,'reassign',{taskId:id,generation:t.assignment_generation,assigneeId:f.second.id});t=f.work.task(f.second,id);assert.equal(t.due_at,due);assert.equal(t.assignment_history.filter(e=>e.event_type==='reassigned').length,1);assert.equal(f.work.snapshot(f.admin,{view:'team',state:'needs_assignment'}).taskPage.total,0);assert.equal(f.work.snapshot(f.second,{view:'mine'}).taskPage.total,1);assert.equal(f.work.snapshot(f.third,{view:'mine'}).taskPage.total,0);const own=f.create(f.third).taskId;f.work.flagInactivity({at:new Date(Date.now()+86400000)});assert.equal(f.work.task(f.third,own).attention,0);f.cmd(f.third,'stop',{taskId:own,generation:f.work.task(f.third,own).assignment_generation});assert.equal(f.work.task(f.third,own).outcome,'cancelled');assert.equal(f.work.snapshot(f.admin).reviewTotal,0);assert.equal(f.work.snapshot(f.third,{view:'history'}).tasks[0].id,own);f.db.close();});
test('server pages all authorized active and older work in batches of 100, monitoring never touches deadlines or activity',()=>{const f=fixture(),active=[];for(let i=0;i<111;i++)active.push(f.create(f.op).taskId);for(let i=0;i<105;i++){const id=f.create(f.op).taskId;f.cmd(f.op,'stop',{taskId:id,generation:f.work.task(f.op,id).assignment_generation});}f.db.prepare('UPDATE tasks SET due_at=? WHERE id=?').run('2020-01-01T00:00:00Z',active[0]);const before=f.db.prepare('SELECT last_touched_at,due_at,assignment_generation FROM tasks WHERE id=?').get(active[0]);const first=f.work.snapshot(f.op,{view:'mine'}),second=f.work.snapshot(f.op,{view:'mine',page:2}),history=f.work.snapshot(f.op,{view:'history',state:'closed',page:2});assert.equal(first.tasks.length,100);assert.equal(first.taskPage.total,111);assert.equal(first.tasks[0].id,active[0]);assert.equal(second.tasks.length,11);assert.equal(new Set([...first.tasks,...second.tasks].map(t=>t.id)).size,111);assert.equal(history.tasks.length,5);assert.equal(history.taskPage.total,105);assert.equal(f.work.snapshot(f.admin,{view:'team',state:'overdue'}).taskPage.total,1);assert.equal(f.work.snapshot(f.third,{view:'mine'}).tasks.length,0);assert.throws(()=>f.work.snapshot(f.op,{view:'team'}),/not permitted/);assert.equal(f.work.task(f.op,active[0]).id,active[0]);assert.deepEqual(f.db.prepare('SELECT last_touched_at,due_at,assignment_generation FROM tasks WHERE id=?').get(active[0]),before);assert.equal(f.work.snapshot(f.admin,{view:'team'}).operators.find(u=>u.id===f.op.id).open,111);f.db.close();});
test('review filters compose by assigned/performed people; Unknown and duplicate display names retain separate identities',()=>{const f=fixture();for(const person of [f.op,f.second,f.third]){const id=f.create(f.admin,{assigneeId:person.id}).taskId;let t=f.work.task(person,id);f.cmd(person,'start',{taskId:id,generation:t.assignment_generation});const l=f.work.task(person,id).lines[0];f.cmd(person,'report',{lineId:l.id,revision:l.revision,cellId:l.cell_id,unit:l.unit_of_measure,quantity:.001,manual:true,reason:'Original paper movement'});}f.cmd(f.admin,'manual',{direction:'put',productId:1,cellId:1,quantity:1,performerId:'unknown',origin:'unknown-slip'});const view=f.work.snapshot(f.admin,{assigned:f.second.id,performed:f.second.id,group:'performed'});assert.equal(view.reviewTotal,4);assert.equal(view.reviewPage.total,1);assert.equal(view.pending[0].performer_username,'second');assert.equal(view.pending[0].reporter_username,'second');assert.equal(view.reviewGroups[0].total,1);assert.equal(f.work.snapshot(f.admin,{performed:'unknown'}).pending.length,1);assert.equal(f.work.snapshot(f.admin,{assigned:f.second.id,performed:f.third.id}).pending.length,0);f.db.close();});
test('maintenance commands reject a service bypass before invoking backup effects',()=>{const f=fixture();let effects=0;const service=createMaintenanceCommands({db:f.db,backupService:{createBackup(){effects++;}}});assert.throws(()=>service.create(f.op,{}),/not permitted/);assert.equal(effects,0);service.create(f.admin,{});assert.equal(effects,1);f.db.close();});

test('an old automatic timeout on provably untouched modern work can retire safely; explicit uncertainty cannot',()=>{const f=fixture(),id=f.create(f.op).taskId,t=f.work.task(f.op,id),l=t.lines[0],rid=randomUUID();f.db.prepare("INSERT INTO work_reports(id,origin_ref,line_id,product_id,cell_id,direction,quantity,unit,reporter_id,status,reason,payload,created_at,quantity_known) VALUES(?,?,?,?,?,? ,0,?,?,'review',?,?,?,0)").run(rid,'attention:'+l.id,l.id,l.product_id,l.cell_id,l.type,l.unit_of_measure,f.op.id,'Inactivity needs verification. Expected quantity is shown for context; enter an actual quantity or keep pending.',JSON.stringify({unknown:true,reason:'Actual quantity is unknown; zero is not a verified answer.'}),new Date().toISOString());f.db.prepare("UPDATE tasks SET attention=1,outcome='needs_review' WHERE id=?").run(id);f.cmd(f.op,'stop',{taskId:id,generation:t.assignment_generation});assert.equal(f.work.task(f.op,id).outcome,'cancelled');assert.equal(f.db.prepare('SELECT status FROM work_reports WHERE id=?').get(rid).status,'resolved');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM transactions').get().n,0);const another=f.create(f.op).taskId,active=f.work.task(f.op,another);f.cmd(f.op,'askReview',{lineId:active.lines[0].id,reason:'I might have moved stock'});f.cmd(f.op,'stop',{taskId:another,generation:active.assignment_generation});assert.equal(f.work.task(f.op,another).outcome,'needs_review');assert.equal(f.work.snapshot(f.admin).reviewTotal,1);f.db.close();});
