import {locationNavigation} from '../operations/navigation.js';
import {can} from "../access/catalog.js";
import {page,escapeHtml as e} from '../../render.js';
import {ensureAuth,ensureApiAuth} from '../../server/http/auth-guards.js';
import {sendHtml,sendJson} from '../../server/http/responses.js';
import {describeLocation,resolveLocationLabel} from '../operations/location-contract.js';
export function locationBrowseRoutes(request,response,url,user,state){
 if(!['/cells','/api/locations/resolve'].includes(url.pathname)&&!/^\/cells\/\d+$/.test(url.pathname))return false;
 if(request.method!=='GET')return false;
 if(!ensureAuth(response,user))return true;
 const {db}=state;
 if(url.pathname==='/api/locations/resolve'){
  if(!ensureApiAuth(response,user))return true;
  const c=resolveLocationLabel(db,state.operationsService.identity().site,url.searchParams.get('label'));
  if(!c)throw new Error('QR not assigned to an active location here. Ask an administrator to assign it in Manage Locations.');
  const all=state.displayCoordinator.view(user),selected=all.find(r=>r.cell.id===c.id);
  const products=(selected?.products||[]).map(p=>({...p,warehouseStock:all.reduce((n,r)=>n+(r.products.find(v=>v.product_id===p.product_id)?.on_hand||0),0),availableToPick:all.reduce((n,r)=>n+(r.products.find(v=>v.product_id===p.product_id)?.available||0),0)}));
  sendJson(response,{cellId:c.id,name:c.display_name||c.logical_code,description:describeLocation(db,c.id),warehouseName:c.warehouse_name,products,canStocktake:can(user,'count.create')||can(user,'count.manage')});return true;
 }
 const rows=state.displayCoordinator.view(user).map(r=>({...r,description:describeLocation(db,r.cell.id)}));
 const detail=url.pathname.match(/^\/cells\/(\d+)$/),selected=detail?rows.find(r=>r.cell.id===Number(detail[1])):null;
 const historyButton=c=>`<button type="button" class="location-history-button" data-cell-history="${c.id}" aria-label="history of movement in this bin/cell" title="history of movement in this bin/cell"><svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 11a9 9 0 1 1 2.6 7M3 5v6h6M12 7v5l3 2"/></svg></button>`;
 const quantityButton=(label,cellId=null,productId=null)=>`<button type="button" class="ghost-button count-button" ${cellId?'data-show-location-count':'data-show-product-quantity'} ${cellId?`data-cell-id="${cellId}"`:''} ${productId?`data-product-id="${productId}"`:''} ${cellId?'':`data-quantity-key="warehouse:all"`} data-activate-endpoint="${cellId?`/api/cells/${cellId}/count`:'/products/quantities'}" data-clear-endpoint="${cellId?`/api/cells/${cellId}/count/clear`:'/products/quantities/clear'}" data-show-label="${e(label)}" data-active-label="Showing quantities" aria-pressed="false">${e(label)}</button>`;
 const locateButton=(c,label='Locate')=>`<button type="button" class="ghost-button locate-button" data-locate-cell data-cell-id="${c.id}" data-show-label="${e(label)}" data-active-label="Locating" aria-pressed="false" ${c.controller_id&&c.hardware_channel?'':'disabled aria-disabled="true" title="No light is mapped to this location"'}>${e(label)}</button>`;
 const pingButton=c=>`<button type="button" class="green-button ping-button" data-ping-cell data-cell-id="${c.id}" ${c.controller_id&&c.hardware_channel?'':'disabled aria-disabled="true" title="No light is mapped to this location"'}>Ping</button>`;
 const actions=c=>`<div class="mini-actions">${locateButton(c)}${pingButton(c)}<a href="/pick?cell_id=${c.id}">Pick</a><a href="/put?cell_id=${c.id}">Put</a>${can(user,'count.create')||can(user,'count.manage')?`<a href="/stocktaking?cellId=${c.id}">Stocktake location</a>`:''}</div>`;
 const stock=r=>r.products.length?r.products.map(p=>`<p><a href="/products/${p.product_id}">${e(p.name)}</a> · On shelf ${e(p.on_hand)} ${e(p.unit_of_measure)} · Reserved ${e(p.reserved_quantity)} · ${p.uncertain?'Needs review':'Available to pick '+e(p.available)}</p>`).join(''):'<p>No recorded stock.</p>';
 let content,title='Locations';
 if(detail){if(!selected)throw new Error('Location not found.');const {cell:c,description}=selected;title=description.name;content=`<a href="/cells">← Locations</a><section class="work-panel"><div class="location-card-heading"><h2>${e(description.name)}</h2>${historyButton(c)}</div><p>${e(description.directions)} · ${e(c.logical_code)}</p>${actions(c)}<p>${quantityButton('Show all quantities in this location',c.id)}</p><details><summary>More · test light and technical details</summary><p>${c.controller_id?'Controller '+e(c.controller_id)+' · Output '+e(c.hardware_channel)+' · '+(c.binding_verified_at?'Physically verified '+e(c.binding_verified_at):'Binding needs physical check'):'Manual location — no mapped light'}</p>${locateButton(c,'Test light')}</details></section><section class="work-panel"><h2>Contents</h2>${stock(selected)}${selected.products.map(p=>`<p>${e(p.name)}: <a href="/pick?cell_id=${c.id}&product_id=${p.product_id}">Pick</a> · <a href="/put?cell_id=${c.id}&product_id=${p.product_id}">Put</a> · ${quantityButton('Show this quantity on LED',c.id,p.product_id)}${can(user,'count.create')||can(user,'count.manage')?` · <a href="/stocktaking?productId=${p.product_id}&cellId=${c.id}">Stocktake this product here</a>`:''}</p>`).join('')}</section>${can(user,'locations.manage')?`<details class="work-panel"><summary>Location settings</summary><a href="/locations/manage">Edit name, QR or LED mapping</a><form data-location-mode="${c.id}"><label>Guidance mode<select name="mode"><option value="exclusive" ${c.guidance_mode==='exclusive'?'selected':''}>Exclusive turn</option><option value="shared" ${c.guidance_mode==='shared'?'selected':''}>Shared consumables</option></select></label><button>Save mode</button><p role="status"></p></form></details>`:''}`;
 }else{const q=(url.searchParams.get('q')||'').toLocaleLowerCase(),filter=url.searchParams.get('filter')||'all',match=r=>(!q||JSON.stringify([r.description,r.products.map(p=>p.name)]).toLocaleLowerCase().includes(q))&&(filter==='stock'?r.products.length:filter==='empty'?!r.products.length:filter==='mapped'?r.cell.controller_id:filter==='manual'?!r.cell.controller_id:true),visible=rows.filter(match);
 content=`<div class="work-toolbar">${quantityButton('Show all quantities — entire warehouse')}${can(user,'locations.manage')?'<a href="/locations/manage">Manage locations</a>':''}</div><div class="work-views">${[['all','All locations',rows.length],['stock','With stock',rows.filter(r=>r.products.length).length],['empty','Empty',rows.filter(r=>!r.products.length).length],['mapped','Mapped',rows.filter(r=>r.cell.controller_id).length],['manual','Manual',rows.filter(r=>!r.cell.controller_id).length]].map(([f,label,n])=>`<a href="/cells?filter=${f}" ${filter===f?'aria-current="page"':''}>${label} · ${n}</a>`).join('')}</div><form class="count-form"><input name="filter" type="hidden" value="${e(filter)}"><label>Search name, code, fields or contents<input name="q" value="${e(q)}"></label><button>Search locations</button></form><button data-browse-scan>Scan location QR</button><div data-browse-camera></div><details><summary>Enter QR text manually</summary><form data-browse-qr><label>Location QR<input name="label" required maxlength="300"></label><button>Open location information</button></form></details><p role="status" data-browse-status></p><p>${visible.length} locations shown · <a href="/labels?cells=${visible.map(r=>r.cell.id).join(',')}">Print labels for these ${visible.length} locations</a> · <a href="/recommended-actions">Space suggestions</a></p><div class="work-grid">${visible.map(r=>`<section class="work-panel"><div class="location-card-heading"><h2><a href="/cells/${r.cell.id}">${e(r.description.name)}</a></h2>${historyButton(r.cell)}</div><p>${e(r.description.directions)} · ${e(r.cell.logical_code)}</p>${stock(r)}${actions(r.cell)}</section>`).join('')}</div>`;
 }
 const identity=state.operationsService.identity();
 content+=`<dialog class="location-history-dialog" data-cell-history-dialog data-actor="${user.id}" data-site="${e(identity.site)}" data-dataset="${e(identity.dataset)}" aria-labelledby="cell-history-title"><header class="review-task-header"><button type="button" class="secondary" data-cell-history-back>← Back</button><h2 id="cell-history-title">Movement history</h2><button type="button" class="dialog-dismiss" data-cell-history-back aria-label="Close movement history" title="Close"><span aria-hidden="true">×</span></button></header><section data-cell-history-content aria-live="polite"></section></dialog>`;
 sendHtml(response,page({title,user,content:locationNavigation(user)+content+'<script src="/client/vendor/jsQR.js"></script><script type="module" src="/client/location-browse.js"></script><script type="module" src="/client/location-history.js"></script>'}));return true;
}
