import {locationHierarchy} from './hierarchy.js';
import {locationTree} from '../../../public/client/location-tree.js';
import {locationNavigation} from '../operations/navigation.js';
import {can} from "../access/catalog.js";
import {page,escapeHtml as e} from '../../render.js';
import {ensureAuth,ensureApiAuth} from '../../server/http/auth-guards.js';
import {sendHtml,sendJson} from '../../server/http/responses.js';
import {describeLocation,resolveLocationLabel} from '../operations/location-contract.js';
export function locationBrowseRoutes(request,response,url,user,state){
 if(!['/cells','/api/locations/resolve','/api/locations/hierarchy'].includes(url.pathname)&&!/^\/cells\/\d+$/.test(url.pathname))return false;
 if(request.method!=='GET')return false;
 if(!ensureAuth(response,user))return true;
 const {db}=state;
 if(url.pathname==='/api/locations/hierarchy'){if(!ensureApiAuth(response,user))return true;state.operationsService.actorNow(user,'locations.manage');sendJson(response,{...locationHierarchy(db),...state.operationsService.identity(),actorId:user.id});return true;}
 if(url.pathname==='/api/locations/resolve'){
  if(!ensureApiAuth(response,user))return true;
  const c=resolveLocationLabel(db,state.operationsService.identity().site,url.searchParams.get('label'));
  if(!c)throw new Error('QR not assigned to an active location here. Ask an administrator to assign it in Manage Locations.');
  const all=state.displayCoordinator.view(user),selected=all.find(r=>r.cell.id===c.id);
  const products=(selected?.products||[]).map(p=>({...p,warehouseStock:all.reduce((n,r)=>n+(r.products.find(v=>v.product_id===p.product_id)?.on_hand||0),0),availableToPick:all.reduce((n,r)=>n+(r.products.find(v=>v.product_id===p.product_id)?.available||0),0)}));
  sendJson(response,{cellId:c.id,name:c.display_name||c.logical_code,description:describeLocation(db,c.id),warehouseName:c.warehouse_name,products,canStocktake:can(user,'count.create')||can(user,'count.manage')});return true;
 }
 const rows=state.displayCoordinator.view(user).map(r=>({...r,description:describeLocation(db,r.cell.id)}));
 const detail=url.pathname.match(/^\/cells\/(\d+)$/),selected=detail?rows.find(r=>r.cell.id===Number(detail[1])):null;
 const historyButton=c=>`<button type="button" class="location-history-button" data-cell-history="${c.id}" aria-label="history of movement in this bin/cell" title="history of movement in this bin/cell"><svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 11a9 9 0 1 1 2.6 7M3 5v6h6M12 7v5l3 2"/></svg></button>`;
 const quantityButton=(label,cellId=null,productId=null)=>`<button type="button" class="ghost-button count-button" ${cellId?'data-show-location-count':'data-show-product-quantity'} ${cellId?`data-cell-id="${cellId}"`:''} ${productId?`data-product-id="${productId}"`:''} ${cellId?'':`data-quantity-key="warehouse:all"`} data-activate-endpoint="${cellId?`/api/cells/${cellId}/count`:'/products/quantities'}" data-clear-endpoint="${cellId?`/api/cells/${cellId}/count/clear`:'/products/quantities/clear'}" data-show-label="${e(label)}" data-active-label="Showing quantities" aria-pressed="false">${e(label)}</button>`;
 const locateButton=(c,label='Locate')=>`<button type="button" class="ghost-button locate-button" data-locate-cell data-cell-id="${c.id}" data-show-label="${e(label)}" data-active-label="Locating" aria-pressed="false" ${c.controller_id&&c.hardware_channel?'':'disabled aria-disabled="true" title="No light is mapped to this location"'}>${e(label)}</button>`;
 const pingButton=c=>`<button type="button" class="green-button ping-button" data-ping-cell data-cell-id="${c.id}" ${c.controller_id&&c.hardware_channel?'':'disabled aria-disabled="true" title="No light is mapped to this location"'}>Ping</button>`;
 const actions=c=>`<div class="mini-actions location-cell-actions">${can(user,'locations.locate')?locateButton(c)+pingButton(c):''}${can(user,'work.pick')?`<a class="ghost-button" href="/pick?cell_id=${c.id}">Pick</a>`:''}${can(user,'work.put')?`<a class="ghost-button" href="/put?cell_id=${c.id}">Put</a>`:''}${can(user,'count.create')||can(user,'count.manage')?`<a class="ghost-button location-stocktake-action" href="/stocktaking?cellId=${c.id}">Stocktake at this location</a>`:''}</div>`;
 const stock=r=>`<div class="location-stock-wrap" tabindex="0" role="region" aria-label="Stock at ${e(r.description.name)}"><table class="my-work-table location-stock-table"><thead><tr>${['Product','SKU','On shelf','Reserved','Available to pick','Total capacity'].map(v=>`<th scope="col">${v}</th>`).join('')}</tr></thead><tbody>${r.products.map(p=>`<tr><td><a href="/products/${p.product_id}">${e(p.name)}</a><small>${e(p.unit_of_measure)}</small></td><td>${e(p.sku)}</td><td>${e(p.on_hand)}</td><td>${e(p.reserved_quantity)}</td><td>${e(p.available)}${p.uncertain?'<small>Needs review</small>':''}</td><td title="Items per location for this product, if this cell holds only this product">${e(p.items_per_cell)}</td></tr>`).join('')||'<tr><td colspan="6">No recorded stock.</td></tr>'}</tbody></table></div>`;
 const stockSummary=r=>`<div class="location-card-products" role="region" aria-label="Products at ${e(r.description.name)}">${r.products.map(p=>`<section class="location-product-summary" aria-label="Product: ${e(p.name)}"><div class="location-product-heading"><a href="/products/${p.product_id}">${e(p.name)}</a><span class="location-product-sku" title="SKU · Unit of measure">${e(p.sku)} · ${e(p.unit_of_measure)}</span></div><dl class="location-product-counts">${[['On shelf',p.on_hand],['Reserved',p.reserved_quantity],['Available to pick',p.available],['Total capacity',p.items_per_cell]].map(([label,value])=>`<div ${label==='Total capacity'?'title="Items per location for this product, if this cell holds only this product"':''}><dt>${label}</dt><dd>${e(value)}</dd></div>`).join('')}</dl>${p.uncertain?'<small class="location-product-warning">Needs review</small>':''}</section>`).join('')||'<div class="location-cell-empty"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m3 7 9-4 9 4v10l-9 4-9-4Z"/><path d="m3 7 9 4 9-4M12 11v10"/></svg><span>No recorded stock</span></div>'}</div>`;
 const locationCard=r=>`<section class="work-panel location-cell-card"><div class="location-card-heading"><div class="location-cell-title"><div class="location-cell-name"><span class="location-level-label">Cell</span><h2><a href="/cells/${r.cell.id}" title="${e(r.description.name)}">${e(r.description.name)}</a></h2></div><p class="location-card-subtitle" title="${e(r.cell.travel_instructions)} · ${e(r.cell.warehouse_name)}">${e(r.cell.travel_instructions)} · ${e(r.cell.warehouse_name)}</p></div>${historyButton(r.cell)}</div>${stockSummary(r)}${actions(r.cell)}</section>`;
 let content,title='Locations';
 if(detail){if(!selected)throw new Error('Location not found.');const {cell:c,description}=selected;title=description.name;content=`<a href="/cells">← Locations</a><section class="work-panel"><div class="location-card-heading"><h2>${e(description.name)}</h2>${historyButton(c)}</div><p>${e(description.directions)} · ${e(c.logical_code)}</p>${actions(c)}<p>${quantityButton('Show all quantities in this location',c.id)}</p><details><summary>More · test light and technical details</summary><p>${c.controller_id?'Controller '+e(c.controller_id)+' · Output '+e(c.hardware_channel)+' · '+(c.binding_verified_at?'Physically verified '+e(c.binding_verified_at):'Binding needs physical check'):'Manual location — no mapped light'}</p>${locateButton(c,'Test light')}</details></section><section class="work-panel"><h2>Contents</h2>${stock(selected)}${selected.products.map(p=>`<p>${e(p.name)}: <a href="/pick?cell_id=${c.id}&product_id=${p.product_id}">Pick</a> · <a href="/put?cell_id=${c.id}&product_id=${p.product_id}">Put</a> · ${quantityButton('Show this quantity on LED',c.id,p.product_id)}${can(user,'count.create')||can(user,'count.manage')?` · <a href="/stocktaking?productId=${p.product_id}&cellId=${c.id}">Stocktake this product here</a>`:''}</p>`).join('')}</section>${can(user,'locations.manage')?`<details class="work-panel"><summary>Location settings</summary><a href="/locations/manage">Edit name, QR or LED mapping</a><form data-location-mode="${c.id}"><label>Guidance mode<select name="mode"><option value="exclusive" ${c.guidance_mode==='exclusive'?'selected':''}>Exclusive turn</option><option value="shared" ${c.guidance_mode==='shared'?'selected':''}>Shared consumables</option></select></label><button>Save mode</button><p role="status"></p></form></details>`:''}`;
 }else{const q=(url.searchParams.get('q')||'').toLocaleLowerCase(),filter=url.searchParams.get('filter')||'all',match=r=>(!q||JSON.stringify([r.description,r.cell.warehouse_name,r.cell.travel_instructions,r.products.map(p=>[p.name,p.sku])]).toLocaleLowerCase().includes(q))&&(filter==='stock'?r.products.length:filter==='empty'?!r.products.length:filter==='mapped'?r.cell.controller_id:filter==='manual'?!r.cell.controller_id:true),visible=rows.filter(match),layout=locationHierarchy(db),cards=Object.fromEntries(rows.map(r=>[r.cell.id,locationCard(r)]));
 content=`<div class="locations-browser"><div class="work-toolbar location-page-tools"><form class="count-form location-search"><input name="filter" type="hidden" value="${e(filter)}"><label>Search locations<input name="q" placeholder="Name, shelf, SKU or product" value="${e(q)}"></label><button>Search</button></form>${quantityButton('Show all quantities — entire warehouse')}${can(user,'locations.manage')?'<a class="ghost-button" href="/locations/manage">Manage locations</a><button type="button" class="secondary" data-edit-layout>Edit</button><button type="button" class="green-button" data-save-layout hidden disabled>Save</button><button type="button" class="secondary" data-cancel-layout hidden>Cancel</button><button type="button" class="secondary" data-add-warehouse hidden>Add warehouse</button>':''}</div><div class="location-browse-secondary"><div class="work-views">${[['all','All locations',rows.length],['stock','With stock',rows.filter(r=>r.products.length).length],['empty','Empty',rows.filter(r=>!r.products.length).length],['mapped','Mapped',rows.filter(r=>r.cell.controller_id).length],['manual','Manual',rows.filter(r=>!r.cell.controller_id).length]].map(([f,label,n])=>`<a href="/cells?filter=${f}" ${filter===f?'aria-current="page"':''}>${label} · ${n}</a>`).join('')}</div><button data-browse-scan>Scan location QR</button><details class="location-qr-manual"><summary>Enter QR text manually</summary><form data-browse-qr><label>Location QR<input name="label" required maxlength="300"></label><button>Open location information</button></form></details></div><div data-browse-camera></div><p role="status" data-browse-status></p><p class="location-results">${visible.length} locations shown · <a href="/labels?cells=${visible.map(r=>r.cell.id).join(',')}">Print labels for these ${visible.length} locations</a> · <a href="/recommended-actions">Space suggestions</a></p><p class="location-layout-hint" data-layout-hint hidden>Drag a cell to a shed/shelf, or a shed/shelf to a warehouse. You can also use the dropdowns.</p><p data-layout-error role="alert" class="form-feedback"></p><div data-location-tree>${locationTree({...layout,cells:layout.cells.filter(c=>visible.some(r=>r.cell.id===c.id))},cards,{showEmpty:!q&&filter==='all'})}</div><script type="application/json" id="location-hierarchy-boot">${JSON.stringify({...layout,...state.operationsService.identity(),actorId:user.id,cards}).replace(/</g,'\\u003c')}</script><script type="module" src="/client/location-hierarchy.js"></script></div>`;
 }
 const identity=state.operationsService.identity();
 content+=`<dialog class="location-history-dialog" data-cell-history-dialog data-actor="${user.id}" data-site="${e(identity.site)}" data-dataset="${e(identity.dataset)}" aria-labelledby="cell-history-title"><header class="review-task-header"><button type="button" class="secondary" data-cell-history-back>← Back</button><h2 id="cell-history-title">Movement history</h2><button type="button" class="dialog-dismiss" data-cell-history-back aria-label="Close movement history" title="Close"><span aria-hidden="true">×</span></button></header><section data-cell-history-content aria-live="polite"></section></dialog>`;
 sendHtml(response,page({title,user,content:locationNavigation(user)+content+'<script src="/client/vendor/jsQR.js"></script><script type="module" src="/client/location-browse.js"></script><script type="module" src="/client/location-history.js"></script>'}));return true;
}
