import {page,escapeHtml as e} from '../../render.js';
import {ensureAuth,ensureApiAuth} from '../../server/http/auth-guards.js';
import {sendHtml,sendJson} from '../../server/http/responses.js';
import {describeLocation,validLocationLabel} from '../operations/location-contract.js';
export function locationBrowseRoutes(request,response,url,user,state){
 if(!['/cells','/api/locations/resolve'].includes(url.pathname)&&!/^\/cells\/\d+$/.test(url.pathname))return false;
 if(request.method!=='GET')return false;
 if(!ensureAuth(response,user))return true;
 const {db}=state;
 if(url.pathname==='/api/locations/resolve'){if(!ensureApiAuth(response,user))return true;const value=url.searchParams.get('label'),token=value?.split(':')[2],c=db.prepare('SELECT *,id AS cell_id FROM cells WHERE label_id=? AND active=1').get(token||'');if(!c||!validLocationLabel(db,state.operationsService.identity().site,c,value))throw new Error('This QR is unknown, unbound, revoked or from another warehouse.');sendJson(response,{cellId:c.id,name:c.display_name||c.logical_code});return true;}
 const rows=state.displayCoordinator.view(user).map(r=>({...r,description:describeLocation(db,r.cell.id)}));
 const detail=url.pathname.match(/^\/cells\/(\d+)$/),selected=detail?rows.find(r=>r.cell.id===Number(detail[1])):null;
 const actions=c=>`<div class="mini-actions"><a href="/quantities?kind=locate&cellId=${c.id}">Locate</a><a href="/pick?cell_id=${c.id}">Pick</a><a href="/put?cell_id=${c.id}">Put</a><a href="/stocktaking?cellId=${c.id}">Check stock</a></div>`;
 const stock=r=>r.products.length?r.products.map(p=>`<p><a href="/products/${p.product_id}">${e(p.name)}</a> · On shelf ${e(p.on_hand)} ${e(p.unit_of_measure)} · Reserved ${e(p.reserved_quantity)} · ${p.uncertain?'Needs review':'Available to pick '+e(p.available)}</p>`).join(''):'<p>No recorded stock.</p>';
 let content,title='Locations';
 if(detail){if(!selected)throw new Error('Location not found.');const {cell:c,description}=selected;title=description.name;content=`<a href="/cells">← Locations</a><section class="work-panel"><h2>${e(description.name)}</h2><p>${e(description.directions)} · ${e(c.logical_code)}</p>${actions(c)}<p><a href="/quantities?cellId=${c.id}">Show all quantities in this location</a></p><details><summary>More · test light and technical details</summary><p>${c.controller_id?'Controller '+e(c.controller_id)+' · Output '+e(c.hardware_channel)+' · '+(c.binding_verified_at?'Physically verified '+e(c.binding_verified_at):'Binding needs physical check'):'Manual location — no mapped light'}</p><a href="/quantities?kind=locate&cellId=${c.id}">Test light</a></details></section><section class="work-panel"><h2>Contents</h2>${stock(selected)}${selected.products.map(p=>`<p>${e(p.name)}: <a href="/pick?cell_id=${c.id}&product_id=${p.product_id}">Pick</a> · <a href="/put?cell_id=${c.id}&product_id=${p.product_id}">Put</a> · <a href="/quantities?cellId=${c.id}&productId=${p.product_id}">Show this quantity on LED</a></p>`).join('')}</section>${user.role==='admin'?`<details class="work-panel"><summary>Location settings</summary><a href="/location-setup?view=details">Edit name, fields or QR</a> · <a href="/devices#cell-mapping">Hardware mapping</a><form data-location-mode="${c.id}"><label>Guidance mode<select name="mode"><option value="exclusive" ${c.guidance_mode==='exclusive'?'selected':''}>Exclusive turn</option><option value="shared" ${c.guidance_mode==='shared'?'selected':''}>Shared consumables</option></select></label><button>Save mode</button><p role="status"></p></form></details>`:''}`;
 }else{const q=(url.searchParams.get('q')||'').toLocaleLowerCase(),filter=url.searchParams.get('filter')||'all',match=r=>(!q||JSON.stringify([r.description,r.products.map(p=>p.name)]).toLocaleLowerCase().includes(q))&&(filter==='stock'?r.products.length:filter==='empty'?!r.products.length:filter==='mapped'?r.cell.controller_id:filter==='manual'?!r.cell.controller_id:true),visible=rows.filter(match);
 content=`<div class="work-toolbar"><a href="/quantities">Show all quantities — entire warehouse</a>${user.role==='admin'?'<a href="/locations/manage">Manage locations</a><a href="/location-setup">Set up locations by scanning</a>':''}</div><div class="work-views">${[['all','All locations',rows.length],['stock','With stock',rows.filter(r=>r.products.length).length],['empty','Empty',rows.filter(r=>!r.products.length).length],['mapped','Mapped',rows.filter(r=>r.cell.controller_id).length],['manual','Manual',rows.filter(r=>!r.cell.controller_id).length]].map(([f,label,n])=>`<a href="/cells?filter=${f}" ${filter===f?'aria-current="page"':''}>${label} · ${n}</a>`).join('')}</div><form class="count-form"><input name="filter" type="hidden" value="${e(filter)}"><label>Search name, code, fields or contents<input name="q" value="${e(q)}"></label><button>Search locations</button></form><button data-browse-scan>Scan location QR</button><div data-browse-camera></div><details><summary>Enter QR text manually</summary><form data-browse-qr><label>Location QR<input name="label" required maxlength="300"></label><button>Open location information</button></form></details><p role="status" data-browse-status></p><p>${visible.length} locations shown · <a href="/labels?cells=${visible.map(r=>r.cell.id).join(',')}">Print labels for these ${visible.length} locations</a> · <a href="/recommended-actions">Space suggestions</a></p><div class="work-grid">${visible.map(r=>`<section class="work-panel"><h2><a href="/cells/${r.cell.id}">${e(r.description.name)}</a></h2><p>${e(r.description.directions)} · ${e(r.cell.logical_code)}</p>${stock(r)}${actions(r.cell)}</section>`).join('')}</div>`;
 }
 sendHtml(response,page({title,user,content:content+'<script src="/client/vendor/jsQR.js"></script><script type="module" src="/client/location-browse.js"></script>'}));return true;
}
