import {can} from '../access/catalog.js';
import {escapeHtml as e,table} from '../../render.js';

const info = values => `<dl class="location-detail-info">${values.map(([label,value])=>`<div><dt>${e(label)}</dt><dd>${e(value??'—')}</dd></div>`).join('')}</dl>`;

export function locationDetailView({user,selected,controller,historyButton,quantityButton,locateButton,pingButton}) {
 const {cell:c,description,products}=selected;
 const stocktake=can(user,'count.create')||can(user,'count.manage');
 const link=(label,href)=>`<a class="ghost-button" href="${e(href)}">${label}</a>`;
 const workActions=productId=>`${can(user,'work.pick')?link('Pick',`/pick?cell_id=${c.id}${productId?`&product_id=${productId}`:''}`):''}${can(user,'work.put')?link('Put',`/put?cell_id=${c.id}${productId?`&product_id=${productId}`:''}`):''}${stocktake?link('Stocktake',`/stocktaking?cellId=${c.id}${productId?`&productId=${productId}`:''}`):''}`;
 const textDisplay=(kind,label,active)=>`<button type="button" class="ghost-button count-button" data-show-product-quantity data-quantity-key="cell:${c.id}:${kind}" data-cell-id="${c.id}" data-display-kind="${kind}" data-activate-endpoint="/api/displays/start" data-clear-endpoint="/api/displays/stop" data-show-label="${label}" data-active-label="${active}" data-active-title="Click again to stop this cell's display." aria-pressed="false" ${c.controller_id&&c.hardware_channel?'':'disabled title="No light is mapped to this location"'}>${label}</button>`;
 const locationInfo=[['Shed / Shelf',c.travel_instructions],['Warehouse',c.warehouse_name],['LED number',c.hardware_channel||'Not mapped']];
 const setupInfo=[['Controller',controller?.controller_code||'Not mapped'],['Cell ID',c.logical_code],['Light mapping',c.binding_verified_at?'Checked':'Not checked'],...description.fields.filter(f=>f.enabled).map(f=>[f.label,JSON.parse(f.value_json)])];
 const productTable=table(['Product','SKU','On shelf','Reserved','Available to pick','Unit','Action'],products.map(p=>[
  `<a href="/products/${p.product_id}">${e(p.name)}</a>${p.uncertain?'<small class="location-product-warning">Needs review</small>':''}`,
  e(p.sku),e(p.on_hand),e(p.reserved_quantity),e(p.available),e(p.unit_of_measure),
  `<div class="mini-actions" role="group" aria-label="Actions for ${e(p.name)}">${workActions(p.product_id)}${can(user,'locations.quantity')?quantityButton('Show quantity',c.id,p.product_id):''}</div>`,
 ]),'No recorded stock');
 const settings=can(user,'locations.manage')?`<dialog class="location-settings-dialog location-detail-settings" data-cell-settings-dialog aria-labelledby="cell-settings-title"><header class="review-task-header"><button type="button" class="secondary" data-cell-settings-close>← Back</button><h2 id="cell-settings-title">Location settings</h2><button type="button" class="dialog-dismiss" data-cell-settings-close aria-label="Close location settings">×</button></header>${info(setupInfo)}<form data-location-mode="${c.id}"><label>Cell access<select name="mode"><option value="exclusive" ${c.guidance_mode==='exclusive'?'selected':''}>One operator at a time</option><option value="shared" ${c.guidance_mode==='shared'?'selected':''}>Shared cell</option></select></label><div class="location-detail-settings-actions"><a class="ghost-button" href="/locations/manage">Edit name, QR and mapping</a><button type="submit">Save</button></div><p role="status" class="form-feedback"></p></form></dialog>`:'';
 return `<div class="location-detail-page"><div class="location-detail-toolbar"><a class="ghost-button" href="/cells">← Locations</a>${can(user,'locations.manage')?'<button type="button" class="ghost-button" data-open-cell-settings>Location settings</button>':''}</div><section class="work-panel location-detail-summary"><header class="location-detail-heading"><h2>Location details</h2>${historyButton(c)}</header>${info(locationInfo)}<div class="location-detail-actions" role="group" aria-label="Work at this location">${workActions()}</div><div class="location-detail-actions location-detail-led-actions" role="group" aria-label="LED controls">${can(user,'locations.locate')?locateButton(c)+pingButton(c)+textDisplay('cell_name','Show cell name','Hide cell name'):''}${can(user,'hardware.test')?textDisplay('module_number','Show LED number','Hide LED number'):''}${can(user,'locations.quantity')?quantityButton('Show quantities',c.id):''}</div></section><section class="work-panel location-detail-contents"><header class="location-detail-heading"><h2>Products <span class="location-detail-count">${products.length}</span></h2></header><div class="product-catalog-table location-detail-table">${productTable}</div></section>${settings}</div>`;
}
