import {saveLocationHierarchy} from './hierarchy.js';
import {assertCan,can} from "../access/catalog.js";
import {randomUUID,createHash} from 'node:crypto';
import {updateCellMapping} from '../../services/inventory.js';
import {withTransaction} from '../../db.js';
import {guardSetupChange} from '../operations/guards.js';
import {describeLocation,saveLocationDescription,locationQrValue} from '../operations/location-contract.js';
const json=JSON.stringify,parse=JSON.parse,now=()=>new Date().toISOString();
export function createLocationSetupService({db,operationsService,displayCoordinator}) {
 const identity=operationsService.identity;
 const actor=a=>operationsService.actorNow(a,"locations.manage");
 const event=(a,type,payload,session=null)=>db.prepare('INSERT INTO location_setup_events(session_id,actor_id,event_type,payload,created_at) VALUES(?,?,?,?,?)').run(session,a.id,type,json(payload),now());
 const controller=id=>{const c=db.prepare('SELECT * FROM controllers WHERE id=? AND active=1').get(Number(id));if(!c||!c.module_count)throw new Error('Register a controller and its output count first.');return c;};
 const signature=c=>json([c.id,c.address,c.module_count,c.configured_at]);
 const fields=()=>db.prepare('SELECT * FROM location_field_definitions ORDER BY display_order,field_key').all();
 const fieldSignature=()=>json(fields().map(f=>[f.field_key,f.revision]));
 function label(value,{enroll=false}={}) {
  if(typeof value!=='string'||!value.trim()||value.length>300||/[\u0000-\u001f\u007f]/.test(value))throw new Error('Use a QR code containing 1–300 readable characters.');
  let l;
  if(value.startsWith('lytguide:')) {
   const [prefix,site,token,revision,...extra]=value.split(':');
   if(site!==identity().site||extra.length)throw new Error('Unsupported label or another warehouse.');
   l=db.prepare('SELECT * FROM location_labels WHERE token=?').get(token);
   if(!l||l.revision!==Number(revision))throw new Error('Unknown LightGuide label. Generate stickers in this warehouse first.');
  } else {
   l=db.prepare('SELECT * FROM location_labels WHERE qr_value=?').get(value);
   if(!l&&enroll){const token=randomUUID();db.prepare("INSERT INTO location_labels(token,qr_value,state,created_at) VALUES(?,?,'unbound',?)").run(token,value,now());l=db.prepare('SELECT * FROM location_labels WHERE token=?').get(token);}
  }
  if(!l)throw new Error('Scan and assign this QR in Manage Locations first.');
  if(l.state==='revoked')throw new Error('This QR was replaced. Use a new sticker.');
  return l;
 }
 function session(a,i,allowChanged=false){const s=db.prepare('SELECT * FROM location_setup_sessions WHERE id=?').get(i.sessionId);if(!s||s.actor_id!==a.id)throw new Error('This setup session belongs to another installer.');if(s.status!=='active'||s.generation!==Number(i.generation))throw new Error('Setup changed. Resume the current output.');const c=allowChanged?null:controller(s.controller_id);if(!allowChanged&&signature(c)!==s.controller_snapshot)throw new Error('Controller configuration changed. Close this setup and revalidate its outputs.');return s;}
 function nextOutput(s){const c=controller(s.controller_id),skipped=parse(s.skipped_json);for(let channel=1;channel<=c.module_count;channel++){if(skipped.includes(channel))continue;const mapped=db.prepare('SELECT * FROM cells WHERE controller_id=? AND hardware_channel=?').get(c.id,channel);if(!mapped?.binding_verified_at)return channel;}return null;}
 function validateValues(attributes={}) {const values={};for(const f of fields().filter(f=>f.enabled)){const value=attributes[f.field_key];if(value==null||String(value).trim()===''){if(f.required)throw new Error(`Enter ${f.label}.`);continue;}if(f.field_type==='number'&&!Number.isFinite(Number(value)))throw new Error(`Enter a number for ${f.label}.`);if(f.field_type==='select'&&!parse(f.options_json).includes(value))throw new Error(`Choose an option for ${f.label}.`);if(String(value).length>300)throw new Error('Keep field values under 300 characters.');values[f.field_key]=f.field_type==='number'?Number(value):String(value).trim();}return values;}
 function newCell(a,name) {const zone=db.prepare('SELECT id FROM zones ORDER BY id LIMIT 1').get();const id=Number(db.prepare(`INSERT INTO cells(logical_code,display_name,zone_id,row_number,column_number,mapping_status,active,capacity) VALUES(?,?,?,1,0,'unmapped',1,12)`).run('LOC-'+randomUUID().slice(0,8).toUpperCase(),name,zone.id).lastInsertRowid);return db.prepare('SELECT * FROM cells WHERE id=?').get(id);}
 function clearOldLabel(cell,a){db.prepare("UPDATE location_labels SET state='revoked' WHERE cell_id=? AND state='bound'").run(cell.id);event(a,'label_revoked',{cellId:cell.id,token:cell.label_id});}
 const actions={
  hierarchy(a,i){const result=saveLocationHierarchy(db,i);event(a,'layout_saved',{changed:result.changed,warehouses:i.warehouses,shelves:i.shelves,cells:i.cells});return result;},
  prepare(a,i){const n=Number(i.quantity);if(!Number.isInteger(n)||n<1||n>200)throw new Error('Prepare 1 to 200 unique stickers.');const tokens=[];for(let x=0;x<n;x++){const token=randomUUID();db.prepare("INSERT INTO location_labels(token,state,created_at) VALUES(?,'unbound',?)").run(token,now());tokens.push(token);}event(a,'labels_prepared',{tokens});return {status:'recorded',tokens,message:`${n} unique unbound stickers prepared.`};},
  enroll(a,i){const tokens=Array.isArray(i.tokens)?i.tokens:[];if(!tokens.length||tokens.length>200||tokens.some(t=>!/^[-a-zA-Z0-9]{12,80}$/.test(t)))throw new Error('Supply a batch of 1–200 unique tokens using letters, numbers and hyphens.');if(new Set(tokens).size!==tokens.length)throw new Error('Duplicate labels in this batch.');for(const token of tokens)db.prepare("INSERT INTO location_labels(token,state,created_at) VALUES(?,'unbound',?)").run(token,now());event(a,'labels_enrolled',{tokens});return {status:'recorded',tokens,message:'Unique supplied tokens enrolled locally. Print the warehouse-scoped QR format.'};},
  field(a,i){const key=i.fieldKey||'field-'+randomUUID(),old=db.prepare('SELECT * FROM location_field_definitions WHERE field_key=?').get(key);if(old&&old.revision!==Number(i.revision))throw new Error('Field changed. Refresh.');const type=i.fieldType;if(!['text','number','select'].includes(type))throw new Error('Choose text, number or selection.');const label=String(i.label||'').trim();if(!label||label.length>80)throw new Error('Use a field label up to 80 characters.');if(old&&old.field_type!==type&&db.prepare('SELECT 1 FROM location_field_values WHERE field_key=?').get(key))throw new Error('A field with saved values cannot change type. Retire it and add a new field with an explicit migration.');const options=(i.options||[]).map(String).map(s=>s.trim()).filter(Boolean);if(type==='select'&&(!options.length||new Set(options).size!==options.length))throw new Error('Provide distinct choices.');if(old&&type==='select'){const used=db.prepare('SELECT value_json FROM location_field_values WHERE field_key=?').all(key).map(v=>parse(v.value_json));if(used.some(v=>!options.includes(v)))throw new Error('Retain choices already used by locations; retire the field to change its meaning.');}
   db.prepare(`INSERT INTO location_field_definitions(field_key,label,field_type,options_json,required,enabled,display_order,use_in_directions) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(field_key) DO UPDATE SET label=excluded.label,field_type=excluded.field_type,options_json=excluded.options_json,required=excluded.required,enabled=excluded.enabled,display_order=excluded.display_order,use_in_directions=excluded.use_in_directions,revision=revision+1`).run(key,label,type,json(options),i.required?1:0,i.enabled===false?0:1,Number(i.displayOrder)||0,i.useInDirections?1:0);
   db.exec('UPDATE cells SET description_revision=description_revision+1');event(a,'field_saved',{key,...i});return {status:'recorded',message:'Field saved. Existing values and issued task directions are preserved.'};},
  details(a,i){const attributes=validateValues(i.attributes);for(const f of fields().filter(f=>f.enabled&&!Object.hasOwn(attributes,f.field_key)))db.prepare('DELETE FROM location_field_values WHERE cell_id=? AND field_key=?').run(Number(i.cellId),f.field_key);const result=saveLocationDescription(db,a,{...i,attributes});event(a,'description_saved',i);return result;},
  manual(a,i){const name=String(i.displayName||'').trim();if(!name)throw new Error('Enter a location name.');const values=validateValues(i.attributes),c=newCell(a,name);saveLocationDescription(db,a,{cellId:c.id,descriptionRevision:c.description_revision,displayName:name,attributes:values,travelInstructions:i.travelInstructions,warehouseName:i.warehouseName});db.prepare("INSERT OR IGNORE INTO location_labels(token,revision,cell_id,state,created_at,bound_at,bound_by) VALUES(?,?,?,'bound',?,?,?)").run(c.label_id,c.label_revision,c.id,now(),now(),a.id);event(a,'manual_location_created',{cellId:c.id});return {status:'recorded',cellId:c.id,message:'Manual location created with stable QR identity.'};},
  start(a,i){const owned=db.prepare("SELECT display_id FROM location_setup_sessions WHERE actor_id=? AND controller_id=? AND status='active'").get(a.id,Number(i.controllerId));guardSetupChange(db,{allowDisplayId:owned?.display_id});const c=controller(i.controllerId),existing=db.prepare("SELECT * FROM location_setup_sessions WHERE controller_id=? AND status='active'").get(c.id);if(existing){if(existing.actor_id!==a.id)throw new Error('Another installer owns setup for this controller.');return {status:'recorded',sessionId:existing.id,message:'Existing setup resumed. Re-light and verify its selected output.'};}const id=randomUUID(),s={controller_id:c.id,skipped_json:'[]'},output=nextOutput(s);if(output==null)throw new Error('All declared outputs are already verified. Use the existing mapping controls for a guarded replacement.');db.prepare('INSERT INTO location_setup_sessions(id,actor_id,controller_id,output,controller_snapshot,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,a.id,c.id,output,signature(c),now(),now());event(a,'setup_started',{controllerId:c.id},id);return {status:'recorded',sessionId:id,message:'Setup started. Light the selected output before pairing.'};},
  skip(a,i){const s=session(a,i);if(!String(i.reason||'').trim())throw new Error('Choose Not lighting or supply a skip reason.');const skipped=[...new Set([...parse(s.skipped_json),s.output])];db.prepare('UPDATE location_setup_sessions SET skipped_json=?,generation=generation+1,display_id=NULL,updated_at=? WHERE id=?').run(json(skipped),now(),s.id);const next=nextOutput({...s,skipped_json:json(skipped)});db.prepare('UPDATE location_setup_sessions SET output=? WHERE id=?').run(next,s.id);event(a,'output_skipped',{output:s.output,reason:i.reason},s.id);return {status:'recorded',oldDisplay:s.display_id,sessionId:s.id,message:'Output left unconfigured. The next eligible light is ready to test.'};},
  retrySkipped(a,i){const s=session(a,i);db.prepare("UPDATE location_setup_sessions SET skipped_json='[]',generation=generation+1,display_id=NULL WHERE id=?").run(s.id);db.prepare('UPDATE location_setup_sessions SET output=? WHERE id=?').run(nextOutput({...s,skipped_json:'[]'}),s.id);return {status:'recorded',oldDisplay:s.display_id,message:'Skipped outputs are available for verification again.'};},
  close(a,i){const s=session(a,i,true);db.prepare("UPDATE location_setup_sessions SET status='closed',generation=generation+1,updated_at=? WHERE id=?").run(now(),s.id);event(a,'setup_closed',{skipped:parse(s.skipped_json)},s.id);return {status:'recorded',oldDisplay:s.display_id,message:'Setup closed. Unverified outputs remain unconfigured.'};},
  bind(a,i){const s=session(a,i);guardSetupChange(db,{allowDisplayId:s.display_id});if(s.output==null)throw new Error('No output selected. Return to skipped lights if needed.');if(i.fieldSignature!==fieldSignature())throw new Error('Location fields changed. Refresh and check the required details.');if(i.physicalConfirmed!==true)throw new Error('Confirm the sticker is beside the light you observed.');const display=db.prepare("SELECT * FROM display_requests WHERE id=? AND actor_id=? AND state='active' AND expires_at>?").get(s.display_id,a.id,now());if(!display)throw new Error('Re-light this output before verifying its physical position.');const l=label(i.label,{enroll:true}),mapped=db.prepare('SELECT * FROM cells WHERE controller_id=? AND hardware_channel=?').get(s.controller_id,s.output);
   if(l.state==='bound'&&(!mapped||l.cell_id!==mapped.id))throw new Error('This sticker already belongs to another location. Open that location; use an explicit guarded replacement.');
   const name=String(i.displayName||'').trim();if(!name)throw new Error('Enter your location name.');const values=validateValues(i.attributes);let c=mapped||newCell(a,name);
   if(mapped&&l.token!==mapped.label_id&&db.prepare('SELECT scanned_at FROM location_labels WHERE token=?').get(mapped.label_id)?.scanned_at&&i.replaceLabel!==true)throw new Error('This output already has a location identity. Explicitly replace its old label, preserving stock and history.');
   if(l.token!==c.label_id)clearOldLabel(c,a);
   db.prepare('UPDATE cells SET controller_id=?,hardware_channel=?,mapping_status=\'mapped\',active=1,label_id=?,label_revision=? WHERE id=?').run(s.controller_id,s.output,l.token,l.revision,c.id);
   db.prepare("UPDATE location_labels SET state='bound',cell_id=?,bound_at=?,bound_by=?,scanned_at=? WHERE token=?").run(c.id,now(),a.id,now(),l.token);
   saveLocationDescription(db,a,{cellId:c.id,descriptionRevision:c.description_revision,displayName:name,travelInstructions:i.travelInstructions,warehouseName:i.warehouseName,attributes:values});
   db.prepare('UPDATE cells SET binding_verified_at=?,binding_verified_by=?,last_mapped_at=?,mapped_by=? WHERE id=?').run(now(),a.id,now(),a.id,c.id);
   event(a,'output_physically_verified',{cellId:c.id,token:l.token,output:s.output,bindingRevision:db.prepare('SELECT binding_revision FROM cells WHERE id=?').get(c.id).binding_revision},s.id);
   db.prepare('UPDATE location_setup_sessions SET generation=generation+1,output=?,display_id=NULL,updated_at=? WHERE id=?').run(nextOutput(s),now(),s.id);
   return {status:'recorded',cellId:c.id,oldDisplay:s.display_id,sessionId:s.id,message:'Location saved with its verified binding. Continue with the next light.'};},
  replace(a,i){guardSetupChange(db,{cellId:Number(i.cellId)});const c=db.prepare('SELECT * FROM cells WHERE id=?').get(Number(i.cellId));if(!c||c.label_revision!==Number(i.labelRevision)||i.confirmed!==true)throw new Error('Refresh and explicitly confirm replacing this label.');const l=label(i.label,{enroll:true});if(l.state!=='unbound')throw new Error('Choose an unbound prepared sticker.');clearOldLabel(c,a);db.prepare('UPDATE cells SET label_id=?,label_revision=?,description_revision=description_revision+1 WHERE id=?').run(l.token,l.revision,c.id);db.prepare("UPDATE location_labels SET state='bound',cell_id=?,bound_at=?,bound_by=?,scanned_at=? WHERE token=?").run(c.id,now(),a.id,now(),l.token);event(a,'label_replaced',{cellId:c.id,oldToken:c.label_id,newToken:l.token});return {status:'recorded',message:'Label replaced; old QR revoked. Cell stock and history are unchanged.'};},
  mapping(a,i){const c=db.prepare('SELECT * FROM cells WHERE id=? AND active=1').get(Number(i.cellId));if(!c||c.binding_revision!==Number(i.bindingRevision))throw new Error('Mapping changed. Reopen this location.');if(i.confirmed!==true)throw new Error('Check the module is at this physical location first.');const source=db.prepare('SELECT c.*,ctrl.module_count,ctrl.active AS controller_active FROM cells c JOIN controllers ctrl ON ctrl.id=c.controller_id WHERE c.id=?').get(Number(i.sourceCellId));if(!source||!source.controller_active||!source.module_count||!Number.isInteger(source.hardware_channel)||source.hardware_channel<1||source.hardware_channel>source.module_count)throw new Error('Configure this controller and its output count first.');const result=updateCellMapping(db,{cellId:source.id,hardwareChannel:source.hardware_channel,targetCellId:c.id,mappedBy:a.id},{withinTransaction:true});event(a,'mapping_saved',{cellId:c.id,controllerId:source.controller_id,output:source.hardware_channel});return {status:'recorded',message:'LED mapping saved. Stock and history stay with this location.'};},
  assignQr(a,i){
   const c=db.prepare('SELECT * FROM cells WHERE id=? AND active=1').get(Number(i.cellId));
   if(!c||c.label_revision!==Number(i.labelRevision)||c.label_id!==i.labelId)throw new Error('Location QR changed. Reopen this location.');
   if(i.confirmed!==true)throw new Error('Confirm you scanned the sticker at this physical location.');
   guardSetupChange(db,{cellId:c.id});
   const l=label(i.label,{enroll:true});
   if(l.state==='bound'&&l.cell_id!==c.id)throw new Error('This QR already belongs to another location. Use a different sticker.');
   if(l.token!==c.label_id){clearOldLabel(c,a);db.prepare('UPDATE cells SET label_id=?,label_revision=?,description_revision=description_revision+1 WHERE id=?').run(l.token,l.revision,c.id);}
   db.prepare("UPDATE location_labels SET state='bound',cell_id=?,bound_at=?,bound_by=?,scanned_at=? WHERE token=?").run(c.id,now(),a.id,now(),l.token);
   event(a,'qr_assigned',{cellId:c.id,oldToken:c.label_id,newToken:l.token});
   return {status:'recorded',message:'QR assigned. Stock and history are unchanged.'};
  },
  revoke(a,i){const l=db.prepare('SELECT * FROM location_labels WHERE token=?').get(i.token);if(!l||l.state==='bound')throw new Error('Replace a bound label explicitly; only unbound stickers can be revoked here.');db.prepare("UPDATE location_labels SET state='revoked' WHERE token=?").run(l.token);event(a,'unbound_label_revoked',{token:l.token});return {status:'recorded',message:'Unused sticker revoked.'};}
 };
 function command(user,action,input){const a=actor(user);const required={hierarchy:'locations.manage',field:'locations.fields',details:'locations.manage',manual:'locations.manage',prepare:'locations.bind',enroll:'locations.bind',start:'locations.bind',skip:'locations.bind',retrySkipped:'locations.bind',close:'locations.bind',bind:'locations.bind',replace:'locations.bind',assignQr:'locations.bind',mapping:'hardware.map',revoke:'locations.bind',light:'locations.bind',previous:'locations.bind'}[action];if(!required)throw new Error('Unknown location setup action.');assertCan(a,required);if(input.actorId!=null&&Number(input.actorId)!==a.id||input.site&&input.site!==identity().site||input.dataset&&input.dataset!==identity().dataset)throw new Error('Saved setup belongs to another account, warehouse or restored dataset. Revalidate the physical output.');if(action==='light'){
   const s=session(a,input);guardSetupChange(db,{allowDisplayId:s.display_id});if(s.display_id)displayCoordinator.stop(a,s.display_id);const c=controller(s.controller_id);if(s.output==null)throw new Error('No output left. Review skipped lights.');
   const mapped=db.prepare('SELECT * FROM cells WHERE controller_id=? AND hardware_channel=?').get(c.id,s.output);
   const target={id:mapped?.id||null,cell_id:mapped?.id||null,controller_id:c.id,controller_address:c.address,hardware_channel:s.output,logical_code:mapped?.logical_code||'Unconfigured output '+s.output,controller_active:c.active,heartbeat_status:c.heartbeat_status};
   const result=displayCoordinator.start(a,{kind:'locate',setupTarget:target,setupSession:s.id,setupGeneration:s.generation},{requestId:input.requestId});if(result.state==='active'&&result.targets.some(t=>t.status==='sent')){db.prepare('UPDATE location_setup_sessions SET display_id=? WHERE id=? AND generation=?').run(result.id,s.id,s.generation);event(a,'output_test_sent',{output:s.output,displayId:result.id},s.id);}return result;
  }
  if(!actions[action])throw new Error('Unknown location setup action.');const id=String(input.requestId||'');if(id.length<8||id.length>160)throw new Error('A stable request identity is required.');const fingerprint=createHash('sha256').update(json({action,input})).digest('hex');const result=withTransaction(db,()=>{actor(a);if(input.actorId!=null&&Number(input.actorId)!==a.id||input.site&&input.site!==identity().site)throw new Error('Saved setup belongs to another account or warehouse.');const old=db.prepare('SELECT * FROM location_setup_receipts WHERE actor_id=? AND request_id=?').get(a.id,id);if(old){if(old.fingerprint!==fingerprint)throw new Error('This setup receipt has different contents.');return {...parse(old.result_json),replayed:true};}const value=actions[action](a,input);db.prepare('INSERT INTO location_setup_receipts VALUES(?,?,?,?)').run(a.id,id,fingerprint,json(value));return value;});if(result.oldDisplay&&!result.replayed)displayCoordinator.stop(a,result.oldDisplay);return result;
 }
 function snapshot(user){const a=actor(user);return {...identity(),user:{id:a.id,name:a.name},capabilities:a.capabilities,fields:fields(),fieldSignature:fieldSignature(),controllers:db.prepare('SELECT id,controller_code,module_count,heartbeat_status FROM controllers WHERE active=1').all(),sessions:db.prepare("SELECT s.*,c.controller_code,c.module_count FROM location_setup_sessions s JOIN controllers c ON c.id=s.controller_id WHERE s.actor_id=? AND s.status='active'").all(a.id),labels:can(a,'locations.bind')?db.prepare('SELECT * FROM location_labels ORDER BY created_at DESC LIMIT 500').all():[],outputs:can(a,'hardware.map')?db.prepare('SELECT c.*,ctrl.controller_code FROM cells c JOIN controllers ctrl ON ctrl.id=c.controller_id WHERE ctrl.active=1 AND c.hardware_channel BETWEEN 1 AND ctrl.module_count ORDER BY ctrl.controller_code,c.hardware_channel').all():[],cells:db.prepare('SELECT * FROM cells WHERE active=1').all().map(c=>({...c,description:describeLocation(db,c.id),hasStock:!!db.prepare('SELECT 1 FROM inventory_balances WHERE cell_id=? AND available_quantity!=0').get(c.id),qrScannedAt:db.prepare('SELECT scanned_at FROM location_labels WHERE token=?').get(c.label_id)?.scanned_at||null,qrValue:locationQrValue(db,identity().site,c),missingFields:fields().filter(f=>f.enabled&&f.required&&!db.prepare('SELECT 1 FROM location_field_values WHERE cell_id=? AND field_key=?').get(c.id,f.field_key)).map(f=>f.label)}))};}
 return {command,snapshot,label};
}
